#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 5

enum {
  anon_sym_LT_QMARK = 1,
  anon_sym_QMARK_GT = 2,
  anon_sym_LT = 3,
  anon_sym_SLASH_GT = 4,
  anon_sym_GT = 5,
  anon_sym_LT_SLASH = 6,
  anon_sym_xmlns = 7,
  anon_sym_COLON = 8,
  aux_sym_attr_value_token1 = 9,
  anon_sym_LT_QMARKxml = 10,
  anon_sym_version = 11,
  anon_sym_encoding = 12,
  sym_name = 13,
  anon_sym_LT_BANG_DASH_DASH = 14,
  anon_sym_DASH_DASH_GT = 15,
  sym_char_data = 16,
  sym_char_ref = 17,
  sym_cdata_start = 18,
  sym_cdata_end = 19,
  anon_sym_AMP = 20,
  sym_eq = 21,
  sym__char = 22,
  sym__ws = 23,
  anon_sym_DQUOTE = 24,
  anon_sym_SQUOTE = 25,
  sym__dec_num = 26,
  sym__encoding = 27,
  sym_xml_file = 28,
  sym_pi = 29,
  sym_element = 30,
  sym_end_tag_element = 31,
  sym_empty_element = 32,
  sym_tag_start = 33,
  sym_tag_end = 34,
  aux_sym__content = 35,
  sym_attribute = 36,
  sym_ns_decl = 37,
  sym_xml_attr = 38,
  sym_attr_value = 39,
  sym_xml_decl = 40,
  sym_xml_version = 41,
  sym_xml_encoding = 42,
  sym_comment = 43,
  sym__cdata_sect = 44,
  sym_cdata = 45,
  sym__ref = 46,
  sym_entity_ref = 47,
  sym__misc = 48,
  sym__quote = 49,
  aux_sym_xml_file_repeat1 = 50,
  aux_sym_pi_repeat1 = 51,
  aux_sym_empty_element_repeat1 = 52,
  aux_sym_attr_value_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_xmlns] = "xmlns",
  [anon_sym_COLON] = ":",
  [aux_sym_attr_value_token1] = "attr_value_token1",
  [anon_sym_LT_QMARKxml] = "<\?xml",
  [anon_sym_version] = "version",
  [anon_sym_encoding] = "encoding",
  [sym_name] = "name",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_char_data] = "char_data",
  [sym_char_ref] = "char_ref",
  [sym_cdata_start] = "cdata_start",
  [sym_cdata_end] = "cdata_end",
  [anon_sym_AMP] = "&",
  [sym_eq] = "eq",
  [sym__char] = "_char",
  [sym__ws] = "_ws",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym__dec_num] = "_dec_num",
  [sym__encoding] = "_encoding",
  [sym_xml_file] = "xml_file",
  [sym_pi] = "pi",
  [sym_element] = "element",
  [sym_end_tag_element] = "end_tag_element",
  [sym_empty_element] = "empty_element",
  [sym_tag_start] = "tag_start",
  [sym_tag_end] = "tag_end",
  [aux_sym__content] = "_content",
  [sym_attribute] = "attribute",
  [sym_ns_decl] = "ns_decl",
  [sym_xml_attr] = "xml_attr",
  [sym_attr_value] = "attr_value",
  [sym_xml_decl] = "xml_decl",
  [sym_xml_version] = "xml_version",
  [sym_xml_encoding] = "xml_encoding",
  [sym_comment] = "comment",
  [sym__cdata_sect] = "_cdata_sect",
  [sym_cdata] = "cdata",
  [sym__ref] = "_ref",
  [sym_entity_ref] = "entity_ref",
  [sym__misc] = "_misc",
  [sym__quote] = "_quote",
  [aux_sym_xml_file_repeat1] = "xml_file_repeat1",
  [aux_sym_pi_repeat1] = "pi_repeat1",
  [aux_sym_empty_element_repeat1] = "empty_element_repeat1",
  [aux_sym_attr_value_repeat1] = "attr_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_xmlns] = anon_sym_xmlns,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_attr_value_token1] = aux_sym_attr_value_token1,
  [anon_sym_LT_QMARKxml] = anon_sym_LT_QMARKxml,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_encoding] = anon_sym_encoding,
  [sym_name] = sym_name,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_char_data] = sym_char_data,
  [sym_char_ref] = sym_char_ref,
  [sym_cdata_start] = sym_cdata_start,
  [sym_cdata_end] = sym_cdata_end,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_eq] = sym_eq,
  [sym__char] = sym__char,
  [sym__ws] = sym__ws,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym__dec_num] = sym__dec_num,
  [sym__encoding] = sym__encoding,
  [sym_xml_file] = sym_xml_file,
  [sym_pi] = sym_pi,
  [sym_element] = sym_element,
  [sym_end_tag_element] = sym_end_tag_element,
  [sym_empty_element] = sym_empty_element,
  [sym_tag_start] = sym_tag_start,
  [sym_tag_end] = sym_tag_end,
  [aux_sym__content] = aux_sym__content,
  [sym_attribute] = sym_attribute,
  [sym_ns_decl] = sym_ns_decl,
  [sym_xml_attr] = sym_xml_attr,
  [sym_attr_value] = sym_attr_value,
  [sym_xml_decl] = sym_xml_decl,
  [sym_xml_version] = sym_xml_version,
  [sym_xml_encoding] = sym_xml_encoding,
  [sym_comment] = sym_comment,
  [sym__cdata_sect] = sym__cdata_sect,
  [sym_cdata] = sym_cdata,
  [sym__ref] = sym__ref,
  [sym_entity_ref] = sym_entity_ref,
  [sym__misc] = sym__misc,
  [sym__quote] = sym__quote,
  [aux_sym_xml_file_repeat1] = aux_sym_xml_file_repeat1,
  [aux_sym_pi_repeat1] = aux_sym_pi_repeat1,
  [aux_sym_empty_element_repeat1] = aux_sym_empty_element_repeat1,
  [aux_sym_attr_value_repeat1] = aux_sym_attr_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_xmlns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attr_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_QMARKxml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_encoding] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_char_data] = {
    .visible = true,
    .named = true,
  },
  [sym_char_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata_start] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__dec_num] = {
    .visible = false,
    .named = true,
  },
  [sym__encoding] = {
    .visible = false,
    .named = true,
  },
  [sym_xml_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pi] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag_element] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_element] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__content] = {
    .visible = false,
    .named = false,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_ns_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_attr] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_value] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_version] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_encoding] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__cdata_sect] = {
    .visible = false,
    .named = true,
  },
  [sym_cdata] = {
    .visible = true,
    .named = true,
  },
  [sym__ref] = {
    .visible = false,
    .named = true,
  },
  [sym_entity_ref] = {
    .visible = true,
    .named = true,
  },
  [sym__misc] = {
    .visible = false,
    .named = true,
  },
  [sym__quote] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_xml_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pi_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_empty_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attr_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_attr_name = 1,
  field_ns_prefix = 2,
  field_tag_name = 3,
  field_xmlns_prefix = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attr_name] = "attr_name",
  [field_ns_prefix] = "ns_prefix",
  [field_tag_name] = "tag_name",
  [field_xmlns_prefix] = "xmlns_prefix",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tag_name, 1},
  [1] =
    {field_attr_name, 0},
  [2] =
    {field_xmlns_prefix, 2},
  [3] =
    {field_attr_name, 2},
    {field_ns_prefix, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 4,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 43,
  [45] = 45,
  [46] = 46,
  [47] = 37,
  [48] = 18,
  [49] = 13,
  [50] = 50,
  [51] = 51,
  [52] = 36,
  [53] = 29,
  [54] = 14,
  [55] = 28,
  [56] = 32,
  [57] = 23,
  [58] = 15,
  [59] = 21,
  [60] = 31,
  [61] = 19,
  [62] = 62,
  [63] = 26,
  [64] = 17,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 66,
  [70] = 70,
  [71] = 68,
  [72] = 72,
  [73] = 67,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 67,
  [78] = 78,
  [79] = 76,
  [80] = 80,
  [81] = 81,
  [82] = 78,
  [83] = 83,
  [84] = 74,
  [85] = 75,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 106,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 99,
  [121] = 121,
  [122] = 112,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 118,
  [127] = 127,
  [128] = 117,
  [129] = 110,
  [130] = 97,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '=') ADVANCE(72);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '-') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '?') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == ']') ADVANCE(77);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(55);
      END_STATE();
    case 5:
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '?') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == 'v') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '[') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(64);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == ';') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == ';') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(50);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(70);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(65);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(69);
      END_STATE();
    case 18:
      if (lookahead == 'C') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 'D') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == ']') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'g') ADVANCE(58);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 37:
      if (lookahead == 'x') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 38:
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 39:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 40:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 43:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '<') ADVANCE(74);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '=') ADVANCE(72);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '?') ADVANCE(13);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead == '?') ADVANCE(46);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '?') ADVANCE(38);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_xmlns);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_attr_value_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LT_QMARKxml);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_encoding);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'l') ADVANCE(61);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'm') ADVANCE(59);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(62);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(53);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_char_data);
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_char_data);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_char_ref);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_cdata_start);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_cdata_end);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '#') ADVANCE(37);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__char);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '?') ADVANCE(46);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '-') ADVANCE(15);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == ']') ADVANCE(14);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__ws);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__dec_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__encoding);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 44},
  [2] = {.lex_state = 66},
  [3] = {.lex_state = 66},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 66},
  [14] = {.lex_state = 66},
  [15] = {.lex_state = 66},
  [16] = {.lex_state = 43},
  [17] = {.lex_state = 66},
  [18] = {.lex_state = 66},
  [19] = {.lex_state = 66},
  [20] = {.lex_state = 66},
  [21] = {.lex_state = 66},
  [22] = {.lex_state = 43},
  [23] = {.lex_state = 66},
  [24] = {.lex_state = 66},
  [25] = {.lex_state = 66},
  [26] = {.lex_state = 66},
  [27] = {.lex_state = 66},
  [28] = {.lex_state = 66},
  [29] = {.lex_state = 66},
  [30] = {.lex_state = 43},
  [31] = {.lex_state = 66},
  [32] = {.lex_state = 66},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 43},
  [35] = {.lex_state = 43},
  [36] = {.lex_state = 66},
  [37] = {.lex_state = 66},
  [38] = {.lex_state = 66},
  [39] = {.lex_state = 66},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 44},
  [42] = {.lex_state = 44},
  [43] = {.lex_state = 44},
  [44] = {.lex_state = 44},
  [45] = {.lex_state = 44},
  [46] = {.lex_state = 44},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 43},
  [49] = {.lex_state = 43},
  [50] = {.lex_state = 44},
  [51] = {.lex_state = 44},
  [52] = {.lex_state = 43},
  [53] = {.lex_state = 43},
  [54] = {.lex_state = 43},
  [55] = {.lex_state = 43},
  [56] = {.lex_state = 43},
  [57] = {.lex_state = 43},
  [58] = {.lex_state = 43},
  [59] = {.lex_state = 43},
  [60] = {.lex_state = 43},
  [61] = {.lex_state = 43},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 43},
  [64] = {.lex_state = 43},
  [65] = {.lex_state = 44},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 44},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 44},
  [72] = {.lex_state = 44},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 44},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 44},
  [80] = {.lex_state = 44},
  [81] = {.lex_state = 44},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 44},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 44},
  [87] = {.lex_state = 44},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 44},
  [90] = {.lex_state = 44},
  [91] = {.lex_state = 44},
  [92] = {.lex_state = 44},
  [93] = {.lex_state = 44},
  [94] = {.lex_state = 44},
  [95] = {.lex_state = 44},
  [96] = {.lex_state = 44},
  [97] = {.lex_state = 40},
  [98] = {.lex_state = 44},
  [99] = {.lex_state = 44},
  [100] = {.lex_state = 44},
  [101] = {.lex_state = 44},
  [102] = {.lex_state = 44},
  [103] = {.lex_state = 44},
  [104] = {.lex_state = 44},
  [105] = {.lex_state = 44},
  [106] = {.lex_state = 40},
  [107] = {.lex_state = 44},
  [108] = {.lex_state = 44},
  [109] = {.lex_state = 44},
  [110] = {.lex_state = 40},
  [111] = {.lex_state = 40},
  [112] = {.lex_state = 44},
  [113] = {.lex_state = 40},
  [114] = {.lex_state = 39},
  [115] = {.lex_state = 5},
  [116] = {.lex_state = 40},
  [117] = {.lex_state = 40},
  [118] = {.lex_state = 44},
  [119] = {.lex_state = 44},
  [120] = {.lex_state = 44},
  [121] = {.lex_state = 44},
  [122] = {.lex_state = 44},
  [123] = {.lex_state = 44},
  [124] = {.lex_state = 44},
  [125] = {.lex_state = 44},
  [126] = {.lex_state = 44},
  [127] = {.lex_state = 44},
  [128] = {.lex_state = 40},
  [129] = {.lex_state = 40},
  [130] = {.lex_state = 40},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_attr_value_token1] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [sym_char_ref] = ACTIONS(1),
    [sym_cdata_start] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym__char] = ACTIONS(1),
    [sym__ws] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_xml_file] = STATE(123),
    [sym_element] = STATE(35),
    [sym_end_tag_element] = STATE(56),
    [sym_empty_element] = STATE(56),
    [sym_tag_start] = STATE(2),
    [sym_xml_decl] = STATE(46),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LT_QMARKxml] = ACTIONS(7),
    [sym__ws] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(19), 1,
      sym_char_data,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(4), 1,
      aux_sym__content,
    STATE(60), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [49] = 14,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_char_data,
    STATE(3), 1,
      sym_tag_start,
    STATE(7), 1,
      aux_sym__content,
    STATE(31), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [98] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(55), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [144] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(18), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [190] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(48), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [236] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(28), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [282] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_tag_start,
    STATE(5), 1,
      aux_sym__content,
    STATE(28), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [328] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(6), 1,
      aux_sym__content,
    STATE(55), 1,
      sym_tag_end,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [374] = 12,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(31), 1,
      anon_sym_LT_QMARK,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(42), 1,
      sym_char_ref,
    ACTIONS(45), 1,
      sym_cdata_start,
    ACTIONS(48), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(32), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [417] = 7,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(51), 1,
      aux_sym_attr_value_token1,
    ACTIONS(53), 1,
      sym_char_ref,
    ACTIONS(55), 1,
      anon_sym_AMP,
    STATE(95), 1,
      sym__quote,
    ACTIONS(57), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(12), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [442] = 7,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(55), 1,
      anon_sym_AMP,
    ACTIONS(59), 1,
      aux_sym_attr_value_token1,
    ACTIONS(61), 1,
      sym_char_ref,
    STATE(92), 1,
      sym__quote,
    ACTIONS(63), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(33), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [467] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(67), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(65), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [483] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(71), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(69), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [499] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(75), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(73), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [515] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(83), 1,
      sym__char,
    STATE(34), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [537] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(87), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(85), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [553] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(91), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(89), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [569] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(95), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(93), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [585] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(101), 1,
      sym_char_data,
    ACTIONS(99), 2,
      anon_sym_LT,
      anon_sym_AMP,
    ACTIONS(97), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [603] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(105), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(103), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [619] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(107), 1,
      sym__char,
    STATE(30), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [641] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(111), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(109), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [657] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(115), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(113), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [673] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(119), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(117), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [689] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(123), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(121), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [705] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(127), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(125), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [721] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(131), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(129), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [737] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(135), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(133), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [753] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(83), 1,
      sym__char,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    STATE(34), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [775] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(141), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(139), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [791] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(145), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(143), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [807] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(147), 1,
      aux_sym_attr_value_token1,
    ACTIONS(150), 1,
      sym_char_ref,
    ACTIONS(153), 1,
      anon_sym_AMP,
    ACTIONS(156), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(33), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [829] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 1,
      anon_sym_LT_QMARK,
    ACTIONS(163), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(166), 1,
      sym__char,
    STATE(34), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [851] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 1,
      sym__char,
    STATE(16), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [873] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(175), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(173), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [889] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(179), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(177), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [905] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(183), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(181), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [921] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(187), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(185), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [937] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(189), 2,
      anon_sym_LT,
      anon_sym_AMP,
    ACTIONS(37), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [952] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(191), 1,
      anon_sym_SLASH_GT,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    STATE(89), 1,
      sym_attribute,
    STATE(93), 2,
      sym_ns_decl,
      sym_xml_attr,
  [975] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    ACTIONS(199), 1,
      anon_sym_SLASH_GT,
    STATE(89), 1,
      sym_attribute,
    STATE(93), 2,
      sym_ns_decl,
      sym_xml_attr,
  [998] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    ACTIONS(201), 1,
      anon_sym_SLASH_GT,
    ACTIONS(203), 1,
      anon_sym_GT,
    STATE(89), 1,
      sym_attribute,
    STATE(93), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1021] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    ACTIONS(203), 1,
      anon_sym_GT,
    ACTIONS(205), 1,
      anon_sym_SLASH_GT,
    STATE(89), 1,
      sym_attribute,
    STATE(93), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1044] = 5,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    STATE(89), 1,
      sym_attribute,
    STATE(93), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1061] = 5,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(207), 1,
      anon_sym_LT,
    STATE(2), 1,
      sym_tag_start,
    STATE(22), 1,
      sym_element,
    STATE(56), 2,
      sym_end_tag_element,
      sym_empty_element,
  [1078] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(179), 2,
      aux_sym_attr_value_token1,
      anon_sym_AMP,
    ACTIONS(177), 3,
      sym_char_ref,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1091] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(91), 1,
      sym__char,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1103] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(67), 1,
      sym__char,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1115] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(11), 1,
      sym__quote,
    STATE(91), 1,
      sym_attr_value,
    ACTIONS(209), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1129] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(11), 1,
      sym__quote,
    STATE(87), 1,
      sym_attr_value,
    ACTIONS(209), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1143] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(175), 1,
      sym__char,
    ACTIONS(173), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1155] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(135), 1,
      sym__char,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1167] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(71), 1,
      sym__char,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1179] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(131), 1,
      sym__char,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1191] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(145), 1,
      sym__char,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1203] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(111), 1,
      sym__char,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1215] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(75), 1,
      sym__char,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1227] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(105), 1,
      sym__char,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1239] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(141), 1,
      sym__char,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1251] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(95), 1,
      sym__char,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1263] = 5,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(211), 1,
      sym_cdata_end,
    ACTIONS(213), 1,
      sym__char,
    STATE(70), 1,
      aux_sym_pi_repeat1,
    STATE(103), 1,
      sym_cdata,
  [1279] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(123), 1,
      sym__char,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1291] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(87), 1,
      sym__char,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1303] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(11), 1,
      sym__quote,
    STATE(96), 1,
      sym_attr_value,
    ACTIONS(209), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1317] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(215), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(217), 1,
      sym__char,
    STATE(82), 1,
      aux_sym_pi_repeat1,
  [1330] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(219), 1,
      anon_sym_QMARK_GT,
    ACTIONS(221), 1,
      sym__char,
    STATE(67), 1,
      aux_sym_pi_repeat1,
  [1343] = 4,
    ACTIONS(224), 1,
      anon_sym_SLASH_GT,
    ACTIONS(226), 1,
      anon_sym_GT,
    ACTIONS(228), 1,
      sym__ws,
    STATE(76), 1,
      aux_sym_empty_element_repeat1,
  [1356] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(230), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(232), 1,
      sym__char,
    STATE(78), 1,
      aux_sym_pi_repeat1,
  [1369] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(234), 1,
      sym_cdata_end,
    ACTIONS(236), 1,
      sym__char,
    STATE(77), 1,
      aux_sym_pi_repeat1,
  [1382] = 4,
    ACTIONS(226), 1,
      anon_sym_GT,
    ACTIONS(238), 1,
      anon_sym_SLASH_GT,
    ACTIONS(240), 1,
      sym__ws,
    STATE(79), 1,
      aux_sym_empty_element_repeat1,
  [1395] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(114), 1,
      sym__quote,
    ACTIONS(242), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1406] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(219), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(244), 1,
      sym__char,
    STATE(73), 1,
      aux_sym_pi_repeat1,
  [1419] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(247), 1,
      anon_sym_QMARK_GT,
    ACTIONS(249), 1,
      sym__char,
    STATE(75), 1,
      aux_sym_pi_repeat1,
  [1432] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(251), 1,
      anon_sym_QMARK_GT,
    ACTIONS(253), 1,
      sym__char,
    STATE(67), 1,
      aux_sym_pi_repeat1,
  [1445] = 4,
    ACTIONS(203), 1,
      anon_sym_GT,
    ACTIONS(205), 1,
      anon_sym_SLASH_GT,
    ACTIONS(255), 1,
      sym__ws,
    STATE(83), 1,
      aux_sym_empty_element_repeat1,
  [1458] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(219), 1,
      sym_cdata_end,
    ACTIONS(257), 1,
      sym__char,
    STATE(77), 1,
      aux_sym_pi_repeat1,
  [1471] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(260), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(262), 1,
      sym__char,
    STATE(73), 1,
      aux_sym_pi_repeat1,
  [1484] = 4,
    ACTIONS(201), 1,
      anon_sym_SLASH_GT,
    ACTIONS(203), 1,
      anon_sym_GT,
    ACTIONS(264), 1,
      sym__ws,
    STATE(83), 1,
      aux_sym_empty_element_repeat1,
  [1497] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(109), 1,
      sym__quote,
    ACTIONS(266), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1508] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(108), 1,
      sym__quote,
    ACTIONS(268), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1519] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(262), 1,
      sym__char,
    ACTIONS(270), 1,
      anon_sym_DASH_DASH_GT,
    STATE(73), 1,
      aux_sym_pi_repeat1,
  [1532] = 3,
    ACTIONS(274), 1,
      sym__ws,
    STATE(83), 1,
      aux_sym_empty_element_repeat1,
    ACTIONS(272), 2,
      anon_sym_SLASH_GT,
      anon_sym_GT,
  [1543] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(277), 1,
      anon_sym_QMARK_GT,
    ACTIONS(279), 1,
      sym__char,
    STATE(85), 1,
      aux_sym_pi_repeat1,
  [1556] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(253), 1,
      sym__char,
    ACTIONS(281), 1,
      anon_sym_QMARK_GT,
    STATE(67), 1,
      aux_sym_pi_repeat1,
  [1569] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(127), 1,
      sym__quote,
    ACTIONS(283), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1580] = 1,
    ACTIONS(285), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1586] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(287), 1,
      anon_sym_QMARK_GT,
    ACTIONS(289), 1,
      anon_sym_encoding,
  [1596] = 1,
    ACTIONS(272), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1602] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(291), 1,
      anon_sym_COLON,
    ACTIONS(293), 1,
      sym_eq,
  [1612] = 1,
    ACTIONS(295), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1618] = 1,
    ACTIONS(297), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1624] = 1,
    ACTIONS(299), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1630] = 3,
    ACTIONS(301), 1,
      anon_sym_QMARK_GT,
    ACTIONS(303), 1,
      sym__ws,
    STATE(100), 1,
      sym_xml_encoding,
  [1640] = 1,
    ACTIONS(305), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1646] = 1,
    ACTIONS(307), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1652] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(309), 1,
      sym_name,
  [1659] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(311), 1,
      anon_sym_COLON,
  [1666] = 2,
    ACTIONS(313), 1,
      anon_sym_QMARK_GT,
    ACTIONS(315), 1,
      sym__ws,
  [1673] = 2,
    ACTIONS(287), 1,
      anon_sym_QMARK_GT,
    ACTIONS(317), 1,
      sym__ws,
  [1680] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(319), 1,
      anon_sym_LT,
  [1687] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(321), 1,
      sym_eq,
  [1694] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(323), 1,
      sym_cdata_end,
  [1701] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(325), 1,
      sym_eq,
  [1708] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(327), 1,
      sym_eq,
  [1715] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(329), 1,
      sym_name,
  [1722] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(331), 1,
      anon_sym_LT,
  [1729] = 1,
    ACTIONS(333), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1734] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(335), 1,
      sym__dec_num,
  [1741] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(337), 1,
      sym_name,
  [1748] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(339), 1,
      sym_name,
  [1755] = 2,
    ACTIONS(341), 1,
      anon_sym_GT,
    ACTIONS(343), 1,
      sym__ws,
  [1762] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(345), 1,
      sym_name,
  [1769] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(347), 1,
      sym__encoding,
  [1776] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(349), 1,
      anon_sym_version,
  [1783] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(351), 1,
      sym_name,
  [1790] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(353), 1,
      sym_name,
  [1797] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(355), 1,
      anon_sym_GT,
  [1804] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(357), 1,
      anon_sym_QMARK_GT,
  [1811] = 2,
    ACTIONS(359), 1,
      anon_sym_QMARK_GT,
    ACTIONS(361), 1,
      sym__ws,
  [1818] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(363), 1,
      sym_eq,
  [1825] = 2,
    ACTIONS(365), 1,
      anon_sym_GT,
    ACTIONS(367), 1,
      sym__ws,
  [1832] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(369), 1,
      ts_builtin_sym_end,
  [1839] = 2,
    ACTIONS(371), 1,
      sym__ws,
    STATE(94), 1,
      sym_xml_version,
  [1846] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(373), 1,
      anon_sym_LT,
  [1853] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(375), 1,
      anon_sym_GT,
  [1860] = 1,
    ACTIONS(377), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1865] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(379), 1,
      sym_name,
  [1872] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(381), 1,
      sym_name,
  [1879] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(383), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 190,
  [SMALL_STATE(7)] = 236,
  [SMALL_STATE(8)] = 282,
  [SMALL_STATE(9)] = 328,
  [SMALL_STATE(10)] = 374,
  [SMALL_STATE(11)] = 417,
  [SMALL_STATE(12)] = 442,
  [SMALL_STATE(13)] = 467,
  [SMALL_STATE(14)] = 483,
  [SMALL_STATE(15)] = 499,
  [SMALL_STATE(16)] = 515,
  [SMALL_STATE(17)] = 537,
  [SMALL_STATE(18)] = 553,
  [SMALL_STATE(19)] = 569,
  [SMALL_STATE(20)] = 585,
  [SMALL_STATE(21)] = 603,
  [SMALL_STATE(22)] = 619,
  [SMALL_STATE(23)] = 641,
  [SMALL_STATE(24)] = 657,
  [SMALL_STATE(25)] = 673,
  [SMALL_STATE(26)] = 689,
  [SMALL_STATE(27)] = 705,
  [SMALL_STATE(28)] = 721,
  [SMALL_STATE(29)] = 737,
  [SMALL_STATE(30)] = 753,
  [SMALL_STATE(31)] = 775,
  [SMALL_STATE(32)] = 791,
  [SMALL_STATE(33)] = 807,
  [SMALL_STATE(34)] = 829,
  [SMALL_STATE(35)] = 851,
  [SMALL_STATE(36)] = 873,
  [SMALL_STATE(37)] = 889,
  [SMALL_STATE(38)] = 905,
  [SMALL_STATE(39)] = 921,
  [SMALL_STATE(40)] = 937,
  [SMALL_STATE(41)] = 952,
  [SMALL_STATE(42)] = 975,
  [SMALL_STATE(43)] = 998,
  [SMALL_STATE(44)] = 1021,
  [SMALL_STATE(45)] = 1044,
  [SMALL_STATE(46)] = 1061,
  [SMALL_STATE(47)] = 1078,
  [SMALL_STATE(48)] = 1091,
  [SMALL_STATE(49)] = 1103,
  [SMALL_STATE(50)] = 1115,
  [SMALL_STATE(51)] = 1129,
  [SMALL_STATE(52)] = 1143,
  [SMALL_STATE(53)] = 1155,
  [SMALL_STATE(54)] = 1167,
  [SMALL_STATE(55)] = 1179,
  [SMALL_STATE(56)] = 1191,
  [SMALL_STATE(57)] = 1203,
  [SMALL_STATE(58)] = 1215,
  [SMALL_STATE(59)] = 1227,
  [SMALL_STATE(60)] = 1239,
  [SMALL_STATE(61)] = 1251,
  [SMALL_STATE(62)] = 1263,
  [SMALL_STATE(63)] = 1279,
  [SMALL_STATE(64)] = 1291,
  [SMALL_STATE(65)] = 1303,
  [SMALL_STATE(66)] = 1317,
  [SMALL_STATE(67)] = 1330,
  [SMALL_STATE(68)] = 1343,
  [SMALL_STATE(69)] = 1356,
  [SMALL_STATE(70)] = 1369,
  [SMALL_STATE(71)] = 1382,
  [SMALL_STATE(72)] = 1395,
  [SMALL_STATE(73)] = 1406,
  [SMALL_STATE(74)] = 1419,
  [SMALL_STATE(75)] = 1432,
  [SMALL_STATE(76)] = 1445,
  [SMALL_STATE(77)] = 1458,
  [SMALL_STATE(78)] = 1471,
  [SMALL_STATE(79)] = 1484,
  [SMALL_STATE(80)] = 1497,
  [SMALL_STATE(81)] = 1508,
  [SMALL_STATE(82)] = 1519,
  [SMALL_STATE(83)] = 1532,
  [SMALL_STATE(84)] = 1543,
  [SMALL_STATE(85)] = 1556,
  [SMALL_STATE(86)] = 1569,
  [SMALL_STATE(87)] = 1580,
  [SMALL_STATE(88)] = 1586,
  [SMALL_STATE(89)] = 1596,
  [SMALL_STATE(90)] = 1602,
  [SMALL_STATE(91)] = 1612,
  [SMALL_STATE(92)] = 1618,
  [SMALL_STATE(93)] = 1624,
  [SMALL_STATE(94)] = 1630,
  [SMALL_STATE(95)] = 1640,
  [SMALL_STATE(96)] = 1646,
  [SMALL_STATE(97)] = 1652,
  [SMALL_STATE(98)] = 1659,
  [SMALL_STATE(99)] = 1666,
  [SMALL_STATE(100)] = 1673,
  [SMALL_STATE(101)] = 1680,
  [SMALL_STATE(102)] = 1687,
  [SMALL_STATE(103)] = 1694,
  [SMALL_STATE(104)] = 1701,
  [SMALL_STATE(105)] = 1708,
  [SMALL_STATE(106)] = 1715,
  [SMALL_STATE(107)] = 1722,
  [SMALL_STATE(108)] = 1729,
  [SMALL_STATE(109)] = 1734,
  [SMALL_STATE(110)] = 1741,
  [SMALL_STATE(111)] = 1748,
  [SMALL_STATE(112)] = 1755,
  [SMALL_STATE(113)] = 1762,
  [SMALL_STATE(114)] = 1769,
  [SMALL_STATE(115)] = 1776,
  [SMALL_STATE(116)] = 1783,
  [SMALL_STATE(117)] = 1790,
  [SMALL_STATE(118)] = 1797,
  [SMALL_STATE(119)] = 1804,
  [SMALL_STATE(120)] = 1811,
  [SMALL_STATE(121)] = 1818,
  [SMALL_STATE(122)] = 1825,
  [SMALL_STATE(123)] = 1832,
  [SMALL_STATE(124)] = 1839,
  [SMALL_STATE(125)] = 1846,
  [SMALL_STATE(126)] = 1853,
  [SMALL_STATE(127)] = 1860,
  [SMALL_STATE(128)] = 1865,
  [SMALL_STATE(129)] = 1872,
  [SMALL_STATE(130)] = 1879,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(129),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(128),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(69),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(20),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(62),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(106),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 4, .production_id = 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 4, .production_id = 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 3, .production_id = 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 3, .production_id = 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 4),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 5, .production_id = 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 5, .production_id = 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag_element, 4),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag_element, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 3, .production_id = 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 3, .production_id = 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__content, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 3, .production_id = 1),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 3, .production_id = 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 4, .production_id = 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 4, .production_id = 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 4, .production_id = 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 4, .production_id = 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cdata_sect, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cdata_sect, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag_element, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag_element, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag_element, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag_element, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(33),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(33),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(116),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attr_value_repeat1, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(110),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(66),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(34),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 1),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 5),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 5),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_ref, 2),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_ref, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cdata_sect, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cdata_sect, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 5, .production_id = 1),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 5, .production_id = 1),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__content, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pi_repeat1, 2),
  [221] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(67),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [244] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(73),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [257] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(77),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_empty_element_repeat1, 2),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_empty_element_repeat1, 2), SHIFT_REPEAT(45),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ns_decl, 5, .production_id = 3),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_attr, 5, .production_id = 4),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_value, 3),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_value, 2),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_attr, 3, .production_id = 2),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 3),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 5),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_version, 6),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [369] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [373] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 4),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_encoding, 6),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_xml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
