#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 136
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_LT_QMARK = 1,
  anon_sym_QMARK_GT = 2,
  anon_sym_LT = 3,
  anon_sym_SLASH_GT = 4,
  anon_sym_GT = 5,
  anon_sym_LT_SLASH = 6,
  anon_sym_xmlns = 7,
  anon_sym_COLON = 8,
  aux_sym_attr_value_token1 = 9,
  anon_sym_xml = 10,
  anon_sym_version = 11,
  anon_sym_encoding = 12,
  sym_name = 13,
  anon_sym_LT_BANG_DASH_DASH = 14,
  anon_sym_DASH_DASH_GT = 15,
  sym_char_data = 16,
  sym_char_ref = 17,
  sym_cdata_start = 18,
  sym_cdata_end = 19,
  anon_sym_AMP = 20,
  anon_sym_SEMI = 21,
  sym_eq = 22,
  sym__char = 23,
  sym__ws = 24,
  anon_sym_DQUOTE = 25,
  anon_sym_SQUOTE = 26,
  sym__dec_num = 27,
  sym__encoding = 28,
  sym_xml_file = 29,
  sym_pi = 30,
  sym_element = 31,
  sym_end_tag_element = 32,
  sym_empty_element = 33,
  sym_tag_start = 34,
  sym_tag_end = 35,
  aux_sym__content = 36,
  sym_attribute = 37,
  sym_ns_decl = 38,
  sym_xml_attr = 39,
  sym_attr_value = 40,
  sym_xml_decl = 41,
  sym_xml_version = 42,
  sym_xml_version_value = 43,
  sym_xml_encoding = 44,
  sym_xml_encoding_value = 45,
  sym_comment = 46,
  sym_cdata_sect = 47,
  sym_cdata = 48,
  sym__ref = 49,
  sym_entity_ref = 50,
  sym__misc = 51,
  sym__quote = 52,
  aux_sym_xml_file_repeat1 = 53,
  aux_sym_pi_repeat1 = 54,
  aux_sym_empty_element_repeat1 = 55,
  aux_sym_attr_value_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_xmlns] = "xmlns",
  [anon_sym_COLON] = ":",
  [aux_sym_attr_value_token1] = "attr_value_token1",
  [anon_sym_xml] = "xml",
  [anon_sym_version] = "version",
  [anon_sym_encoding] = "encoding",
  [sym_name] = "name",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_char_data] = "char_data",
  [sym_char_ref] = "char_ref",
  [sym_cdata_start] = "cdata_start",
  [sym_cdata_end] = "cdata_end",
  [anon_sym_AMP] = "&",
  [anon_sym_SEMI] = ";",
  [sym_eq] = "eq",
  [sym__char] = "_char",
  [sym__ws] = "_ws",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym__dec_num] = "_dec_num",
  [sym__encoding] = "_encoding",
  [sym_xml_file] = "xml_file",
  [sym_pi] = "pi",
  [sym_element] = "element",
  [sym_end_tag_element] = "end_tag_element",
  [sym_empty_element] = "empty_element",
  [sym_tag_start] = "tag_start",
  [sym_tag_end] = "tag_end",
  [aux_sym__content] = "_content",
  [sym_attribute] = "attribute",
  [sym_ns_decl] = "ns_decl",
  [sym_xml_attr] = "xml_attr",
  [sym_attr_value] = "attr_value",
  [sym_xml_decl] = "xml_decl",
  [sym_xml_version] = "xml_version",
  [sym_xml_version_value] = "xml_version_value",
  [sym_xml_encoding] = "xml_encoding",
  [sym_xml_encoding_value] = "xml_encoding_value",
  [sym_comment] = "comment",
  [sym_cdata_sect] = "cdata_sect",
  [sym_cdata] = "cdata",
  [sym__ref] = "_ref",
  [sym_entity_ref] = "entity_ref",
  [sym__misc] = "_misc",
  [sym__quote] = "_quote",
  [aux_sym_xml_file_repeat1] = "xml_file_repeat1",
  [aux_sym_pi_repeat1] = "pi_repeat1",
  [aux_sym_empty_element_repeat1] = "empty_element_repeat1",
  [aux_sym_attr_value_repeat1] = "attr_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_xmlns] = anon_sym_xmlns,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_attr_value_token1] = aux_sym_attr_value_token1,
  [anon_sym_xml] = anon_sym_xml,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_encoding] = anon_sym_encoding,
  [sym_name] = sym_name,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_char_data] = sym_char_data,
  [sym_char_ref] = sym_char_ref,
  [sym_cdata_start] = sym_cdata_start,
  [sym_cdata_end] = sym_cdata_end,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_eq] = sym_eq,
  [sym__char] = sym__char,
  [sym__ws] = sym__ws,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym__dec_num] = sym__dec_num,
  [sym__encoding] = sym__encoding,
  [sym_xml_file] = sym_xml_file,
  [sym_pi] = sym_pi,
  [sym_element] = sym_element,
  [sym_end_tag_element] = sym_end_tag_element,
  [sym_empty_element] = sym_empty_element,
  [sym_tag_start] = sym_tag_start,
  [sym_tag_end] = sym_tag_end,
  [aux_sym__content] = aux_sym__content,
  [sym_attribute] = sym_attribute,
  [sym_ns_decl] = sym_ns_decl,
  [sym_xml_attr] = sym_xml_attr,
  [sym_attr_value] = sym_attr_value,
  [sym_xml_decl] = sym_xml_decl,
  [sym_xml_version] = sym_xml_version,
  [sym_xml_version_value] = sym_xml_version_value,
  [sym_xml_encoding] = sym_xml_encoding,
  [sym_xml_encoding_value] = sym_xml_encoding_value,
  [sym_comment] = sym_comment,
  [sym_cdata_sect] = sym_cdata_sect,
  [sym_cdata] = sym_cdata,
  [sym__ref] = sym__ref,
  [sym_entity_ref] = sym_entity_ref,
  [sym__misc] = sym__misc,
  [sym__quote] = sym__quote,
  [aux_sym_xml_file_repeat1] = aux_sym_xml_file_repeat1,
  [aux_sym_pi_repeat1] = aux_sym_pi_repeat1,
  [aux_sym_empty_element_repeat1] = aux_sym_empty_element_repeat1,
  [aux_sym_attr_value_repeat1] = aux_sym_attr_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_xmlns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attr_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_xml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_encoding] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_char_data] = {
    .visible = true,
    .named = true,
  },
  [sym_char_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata_start] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__dec_num] = {
    .visible = false,
    .named = true,
  },
  [sym__encoding] = {
    .visible = false,
    .named = true,
  },
  [sym_xml_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pi] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag_element] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_element] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__content] = {
    .visible = false,
    .named = false,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_ns_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_attr] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_value] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_version] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_version_value] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_encoding] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_encoding_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata_sect] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata] = {
    .visible = true,
    .named = true,
  },
  [sym__ref] = {
    .visible = false,
    .named = true,
  },
  [sym_entity_ref] = {
    .visible = true,
    .named = true,
  },
  [sym__misc] = {
    .visible = false,
    .named = true,
  },
  [sym__quote] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_xml_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pi_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_empty_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attr_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_attr_name = 1,
  field_decl = 2,
  field_encoding_attr = 3,
  field_ns_prefix = 4,
  field_tag_name = 5,
  field_version_attr = 6,
  field_xmlns_prefix = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attr_name] = "attr_name",
  [field_decl] = "decl",
  [field_encoding_attr] = "encoding_attr",
  [field_ns_prefix] = "ns_prefix",
  [field_tag_name] = "tag_name",
  [field_version_attr] = "version_attr",
  [field_xmlns_prefix] = "xmlns_prefix",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tag_name, 1},
  [1] =
    {field_decl, 1},
  [2] =
    {field_version_attr, 1},
  [3] =
    {field_attr_name, 0},
  [4] =
    {field_encoding_attr, 1},
  [5] =
    {field_xmlns_prefix, 2},
  [6] =
    {field_attr_name, 2},
    {field_ns_prefix, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 7,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 42,
  [44] = 41,
  [45] = 45,
  [46] = 28,
  [47] = 47,
  [48] = 20,
  [49] = 14,
  [50] = 50,
  [51] = 26,
  [52] = 25,
  [53] = 53,
  [54] = 18,
  [55] = 55,
  [56] = 16,
  [57] = 31,
  [58] = 15,
  [59] = 59,
  [60] = 35,
  [61] = 32,
  [62] = 19,
  [63] = 63,
  [64] = 13,
  [65] = 37,
  [66] = 29,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 69,
  [73] = 70,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 74,
  [78] = 78,
  [79] = 74,
  [80] = 80,
  [81] = 80,
  [82] = 82,
  [83] = 75,
  [84] = 84,
  [85] = 76,
  [86] = 68,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 124,
  [126] = 108,
  [127] = 121,
  [128] = 123,
  [129] = 129,
  [130] = 116,
  [131] = 131,
  [132] = 132,
  [133] = 110,
  [134] = 132,
  [135] = 131,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '&') ADVANCE(70);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == ';') ADVANCE(71);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '=') ADVANCE(72);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '-') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '?') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == ']') ADVANCE(77);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '&') ADVANCE(70);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(54);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '[') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(63);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == ';') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == ';') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(49);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(69);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(64);
      END_STATE();
    case 15:
      if (lookahead == '?') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'v') ADVANCE(25);
      if (lookahead == 'x') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'C') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 'D') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == '[') ADVANCE(68);
      END_STATE();
    case 22:
      if (lookahead == ']') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'g') ADVANCE(57);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 30:
      if (lookahead == 'm') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 38:
      if (lookahead == 'x') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 39:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 40:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 43:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') ADVANCE(78);
      if (lookahead == '<') ADVANCE(74);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '&') ADVANCE(70);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == ';') ADVANCE(71);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '=') ADVANCE(72);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == '?') ADVANCE(12);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == 'x') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '?') ADVANCE(46);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_xmlns);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_attr_value_token1);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_xml);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_encoding);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'l') ADVANCE(60);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'm') ADVANCE(58);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(61);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(52);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_char_data);
      if (lookahead == '&') ADVANCE(70);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_char_data);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_char_ref);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_cdata_start);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_cdata_end);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '#') ADVANCE(38);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__char);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '?') ADVANCE(46);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '-') ADVANCE(14);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == ']') ADVANCE(13);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__ws);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__dec_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__encoding);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 44},
  [2] = {.lex_state = 65},
  [3] = {.lex_state = 65},
  [4] = {.lex_state = 44},
  [5] = {.lex_state = 44},
  [6] = {.lex_state = 44},
  [7] = {.lex_state = 44},
  [8] = {.lex_state = 44},
  [9] = {.lex_state = 44},
  [10] = {.lex_state = 44},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 65},
  [14] = {.lex_state = 65},
  [15] = {.lex_state = 65},
  [16] = {.lex_state = 65},
  [17] = {.lex_state = 43},
  [18] = {.lex_state = 65},
  [19] = {.lex_state = 65},
  [20] = {.lex_state = 65},
  [21] = {.lex_state = 65},
  [22] = {.lex_state = 65},
  [23] = {.lex_state = 43},
  [24] = {.lex_state = 65},
  [25] = {.lex_state = 65},
  [26] = {.lex_state = 65},
  [27] = {.lex_state = 65},
  [28] = {.lex_state = 65},
  [29] = {.lex_state = 65},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 65},
  [32] = {.lex_state = 65},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 65},
  [35] = {.lex_state = 65},
  [36] = {.lex_state = 65},
  [37] = {.lex_state = 65},
  [38] = {.lex_state = 43},
  [39] = {.lex_state = 43},
  [40] = {.lex_state = 44},
  [41] = {.lex_state = 44},
  [42] = {.lex_state = 44},
  [43] = {.lex_state = 44},
  [44] = {.lex_state = 44},
  [45] = {.lex_state = 44},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 44},
  [48] = {.lex_state = 43},
  [49] = {.lex_state = 43},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 43},
  [52] = {.lex_state = 43},
  [53] = {.lex_state = 44},
  [54] = {.lex_state = 43},
  [55] = {.lex_state = 44},
  [56] = {.lex_state = 43},
  [57] = {.lex_state = 43},
  [58] = {.lex_state = 43},
  [59] = {.lex_state = 44},
  [60] = {.lex_state = 43},
  [61] = {.lex_state = 43},
  [62] = {.lex_state = 43},
  [63] = {.lex_state = 44},
  [64] = {.lex_state = 43},
  [65] = {.lex_state = 43},
  [66] = {.lex_state = 43},
  [67] = {.lex_state = 44},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 44},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 44},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 44},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 44},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 44},
  [83] = {.lex_state = 44},
  [84] = {.lex_state = 44},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 44},
  [88] = {.lex_state = 44},
  [89] = {.lex_state = 44},
  [90] = {.lex_state = 44},
  [91] = {.lex_state = 44},
  [92] = {.lex_state = 44},
  [93] = {.lex_state = 44},
  [94] = {.lex_state = 44},
  [95] = {.lex_state = 44},
  [96] = {.lex_state = 15},
  [97] = {.lex_state = 44},
  [98] = {.lex_state = 44},
  [99] = {.lex_state = 39},
  [100] = {.lex_state = 44},
  [101] = {.lex_state = 44},
  [102] = {.lex_state = 44},
  [103] = {.lex_state = 44},
  [104] = {.lex_state = 44},
  [105] = {.lex_state = 44},
  [106] = {.lex_state = 15},
  [107] = {.lex_state = 44},
  [108] = {.lex_state = 40},
  [109] = {.lex_state = 44},
  [110] = {.lex_state = 40},
  [111] = {.lex_state = 44},
  [112] = {.lex_state = 40},
  [113] = {.lex_state = 40},
  [114] = {.lex_state = 44},
  [115] = {.lex_state = 44},
  [116] = {.lex_state = 44},
  [117] = {.lex_state = 44},
  [118] = {.lex_state = 44},
  [119] = {.lex_state = 44},
  [120] = {.lex_state = 44},
  [121] = {.lex_state = 44},
  [122] = {.lex_state = 44},
  [123] = {.lex_state = 44},
  [124] = {.lex_state = 44},
  [125] = {.lex_state = 44},
  [126] = {.lex_state = 40},
  [127] = {.lex_state = 44},
  [128] = {.lex_state = 44},
  [129] = {.lex_state = 15},
  [130] = {.lex_state = 44},
  [131] = {.lex_state = 40},
  [132] = {.lex_state = 40},
  [133] = {.lex_state = 40},
  [134] = {.lex_state = 40},
  [135] = {.lex_state = 40},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_attr_value_token1] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [sym_char_ref] = ACTIONS(1),
    [sym_cdata_start] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym__char] = ACTIONS(1),
    [sym__ws] = ACTIONS(3),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_xml_file] = STATE(120),
    [sym_element] = STATE(39),
    [sym_end_tag_element] = STATE(66),
    [sym_empty_element] = STATE(66),
    [sym_tag_start] = STATE(3),
    [sym_xml_decl] = STATE(47),
    [anon_sym_LT_QMARK] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [sym__ws] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(19), 1,
      sym_char_data,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(2), 1,
      sym_tag_start,
    STATE(6), 1,
      aux_sym__content,
    STATE(26), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [49] = 14,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_char_data,
    STATE(2), 1,
      sym_tag_start,
    STATE(4), 1,
      aux_sym__content,
    STATE(51), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [98] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(48), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [144] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(2), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(35), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [190] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(2), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(20), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [236] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(2), 1,
      sym_tag_start,
    STATE(5), 1,
      aux_sym__content,
    STATE(20), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [282] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_tag_start,
    STATE(9), 1,
      aux_sym__content,
    STATE(48), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [328] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(60), 1,
      sym_tag_end,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [374] = 12,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(31), 1,
      anon_sym_LT_QMARK,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(42), 1,
      sym_char_ref,
    ACTIONS(45), 1,
      sym_cdata_start,
    ACTIONS(48), 1,
      anon_sym_AMP,
    STATE(2), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(29), 2,
      sym_end_tag_element,
      sym_empty_element,
    STATE(21), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym_cdata_sect,
      sym__ref,
      sym_entity_ref,
  [417] = 7,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(51), 1,
      aux_sym_attr_value_token1,
    ACTIONS(53), 1,
      sym_char_ref,
    ACTIONS(55), 1,
      anon_sym_AMP,
    STATE(88), 1,
      sym__quote,
    ACTIONS(57), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(30), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [442] = 7,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(55), 1,
      anon_sym_AMP,
    ACTIONS(59), 1,
      aux_sym_attr_value_token1,
    ACTIONS(61), 1,
      sym_char_ref,
    STATE(94), 1,
      sym__quote,
    ACTIONS(63), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(11), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [467] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(67), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(65), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [483] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(71), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(69), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [499] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(75), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(73), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [515] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(79), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(77), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [531] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      anon_sym_LT_QMARK,
    ACTIONS(85), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(87), 1,
      sym__char,
    STATE(33), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [553] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(91), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(89), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [569] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(95), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(93), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [585] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(99), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(97), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [601] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(105), 1,
      sym_char_data,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_AMP,
    ACTIONS(101), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [619] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(109), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(107), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [635] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      anon_sym_LT_QMARK,
    ACTIONS(85), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(111), 1,
      sym__char,
    STATE(38), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [657] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(115), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(113), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [673] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(119), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(117), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [689] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(123), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(121), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [705] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(127), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(125), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [721] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(131), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(129), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [737] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(135), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(133), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [753] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(137), 1,
      aux_sym_attr_value_token1,
    ACTIONS(140), 1,
      sym_char_ref,
    ACTIONS(143), 1,
      anon_sym_AMP,
    ACTIONS(146), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(30), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [775] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(150), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(148), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [791] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(154), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(152), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [807] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      anon_sym_LT_QMARK,
    ACTIONS(161), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(164), 1,
      sym__char,
    STATE(33), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [829] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(169), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(167), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [845] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(173), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(171), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [861] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(177), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(175), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [877] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(181), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(179), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [893] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(83), 1,
      anon_sym_LT_QMARK,
    ACTIONS(85), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(87), 1,
      sym__char,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    STATE(33), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [915] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(83), 1,
      anon_sym_LT_QMARK,
    ACTIONS(85), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(187), 1,
      sym__char,
    STATE(17), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [937] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(189), 2,
      anon_sym_LT,
      anon_sym_AMP,
    ACTIONS(37), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [952] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(191), 1,
      anon_sym_SLASH_GT,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    STATE(93), 1,
      sym_attribute,
    STATE(91), 2,
      sym_ns_decl,
      sym_xml_attr,
  [975] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    ACTIONS(199), 1,
      anon_sym_SLASH_GT,
    ACTIONS(201), 1,
      anon_sym_GT,
    STATE(93), 1,
      sym_attribute,
    STATE(91), 2,
      sym_ns_decl,
      sym_xml_attr,
  [998] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(203), 1,
      anon_sym_SLASH_GT,
    STATE(93), 1,
      sym_attribute,
    STATE(91), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1021] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(193), 1,
      anon_sym_GT,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    ACTIONS(205), 1,
      anon_sym_SLASH_GT,
    STATE(93), 1,
      sym_attribute,
    STATE(91), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1044] = 5,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(195), 1,
      anon_sym_xmlns,
    ACTIONS(197), 1,
      sym_name,
    STATE(93), 1,
      sym_attribute,
    STATE(91), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1061] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(131), 2,
      aux_sym_attr_value_token1,
      anon_sym_AMP,
    ACTIONS(129), 3,
      sym_char_ref,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1074] = 5,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(207), 1,
      anon_sym_LT,
    STATE(3), 1,
      sym_tag_start,
    STATE(23), 1,
      sym_element,
    STATE(66), 2,
      sym_end_tag_element,
      sym_empty_element,
  [1091] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(99), 1,
      sym__char,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1103] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(71), 1,
      sym__char,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1115] = 5,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(209), 1,
      sym_cdata_end,
    ACTIONS(211), 1,
      sym__char,
    STATE(71), 1,
      aux_sym_pi_repeat1,
    STATE(122), 1,
      sym_cdata,
  [1131] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(123), 1,
      sym__char,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1143] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(119), 1,
      sym__char,
    ACTIONS(117), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1155] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(12), 1,
      sym__quote,
    STATE(92), 1,
      sym_attr_value,
    ACTIONS(213), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1169] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(91), 1,
      sym__char,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1181] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(12), 1,
      sym__quote,
    STATE(87), 1,
      sym_attr_value,
    ACTIONS(213), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1195] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(79), 1,
      sym__char,
    ACTIONS(77), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1207] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(150), 1,
      sym__char,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1219] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(75), 1,
      sym__char,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1231] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(99), 1,
      sym__quote,
    STATE(109), 1,
      sym_xml_encoding_value,
    ACTIONS(215), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1245] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(173), 1,
      sym__char,
    ACTIONS(171), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1257] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(154), 1,
      sym__char,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1269] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(95), 1,
      sym__char,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1281] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(105), 1,
      sym_xml_version_value,
    STATE(107), 1,
      sym__quote,
    ACTIONS(217), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1295] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(67), 1,
      sym__char,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1307] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(181), 1,
      sym__char,
    ACTIONS(179), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1319] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(135), 1,
      sym__char,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1331] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(12), 1,
      sym__quote,
    STATE(95), 1,
      sym_attr_value,
    ACTIONS(213), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1345] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(219), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(221), 1,
      sym__char,
    STATE(79), 1,
      aux_sym_pi_repeat1,
  [1358] = 4,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(203), 1,
      anon_sym_SLASH_GT,
    ACTIONS(223), 1,
      sym__ws,
    STATE(84), 1,
      aux_sym_empty_element_repeat1,
  [1371] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(225), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(227), 1,
      sym__char,
    STATE(86), 1,
      aux_sym_pi_repeat1,
  [1384] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(229), 1,
      sym_cdata_end,
    ACTIONS(231), 1,
      sym__char,
    STATE(74), 1,
      aux_sym_pi_repeat1,
  [1397] = 4,
    ACTIONS(199), 1,
      anon_sym_SLASH_GT,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(233), 1,
      sym__ws,
    STATE(84), 1,
      aux_sym_empty_element_repeat1,
  [1410] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(235), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(237), 1,
      sym__char,
    STATE(68), 1,
      aux_sym_pi_repeat1,
  [1423] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(239), 1,
      sym_cdata_end,
    ACTIONS(241), 1,
      sym__char,
    STATE(74), 1,
      aux_sym_pi_repeat1,
  [1436] = 4,
    ACTIONS(244), 1,
      anon_sym_SLASH_GT,
    ACTIONS(246), 1,
      anon_sym_GT,
    ACTIONS(248), 1,
      sym__ws,
    STATE(72), 1,
      aux_sym_empty_element_repeat1,
  [1449] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(250), 1,
      anon_sym_QMARK_GT,
    ACTIONS(252), 1,
      sym__char,
    STATE(77), 1,
      aux_sym_pi_repeat1,
  [1462] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(239), 1,
      anon_sym_QMARK_GT,
    ACTIONS(254), 1,
      sym__char,
    STATE(77), 1,
      aux_sym_pi_repeat1,
  [1475] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(104), 1,
      sym__quote,
    ACTIONS(257), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1486] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(239), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(259), 1,
      sym__char,
    STATE(79), 1,
      aux_sym_pi_repeat1,
  [1499] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(262), 1,
      anon_sym_QMARK_GT,
    ACTIONS(264), 1,
      sym__char,
    STATE(85), 1,
      aux_sym_pi_repeat1,
  [1512] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(266), 1,
      anon_sym_QMARK_GT,
    ACTIONS(268), 1,
      sym__char,
    STATE(76), 1,
      aux_sym_pi_repeat1,
  [1525] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(98), 1,
      sym__quote,
    ACTIONS(270), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1536] = 4,
    ACTIONS(246), 1,
      anon_sym_GT,
    ACTIONS(272), 1,
      anon_sym_SLASH_GT,
    ACTIONS(274), 1,
      sym__ws,
    STATE(69), 1,
      aux_sym_empty_element_repeat1,
  [1549] = 3,
    ACTIONS(278), 1,
      sym__ws,
    STATE(84), 1,
      aux_sym_empty_element_repeat1,
    ACTIONS(276), 2,
      anon_sym_SLASH_GT,
      anon_sym_GT,
  [1560] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(252), 1,
      sym__char,
    ACTIONS(281), 1,
      anon_sym_QMARK_GT,
    STATE(77), 1,
      aux_sym_pi_repeat1,
  [1573] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(221), 1,
      sym__char,
    ACTIONS(283), 1,
      anon_sym_DASH_DASH_GT,
    STATE(79), 1,
      aux_sym_pi_repeat1,
  [1586] = 1,
    ACTIONS(285), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1592] = 1,
    ACTIONS(287), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1598] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(289), 1,
      anon_sym_COLON,
    ACTIONS(291), 1,
      sym_eq,
  [1608] = 3,
    ACTIONS(293), 1,
      anon_sym_QMARK_GT,
    ACTIONS(295), 1,
      sym__ws,
    STATE(118), 1,
      sym_xml_encoding,
  [1618] = 1,
    ACTIONS(297), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1624] = 1,
    ACTIONS(299), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1630] = 1,
    ACTIONS(276), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1636] = 1,
    ACTIONS(301), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1642] = 1,
    ACTIONS(303), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1648] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(305), 1,
      anon_sym_QMARK_GT,
    ACTIONS(307), 1,
      anon_sym_encoding,
  [1658] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(309), 1,
      anon_sym_LT,
  [1665] = 1,
    ACTIONS(311), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1670] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(313), 1,
      sym__encoding,
  [1677] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(315), 1,
      anon_sym_LT,
  [1684] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(317), 1,
      sym_eq,
  [1691] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(319), 1,
      sym_eq,
  [1698] = 2,
    ACTIONS(321), 1,
      sym__ws,
    STATE(90), 1,
      sym_xml_version,
  [1705] = 1,
    ACTIONS(323), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1710] = 1,
    ACTIONS(325), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1715] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(327), 1,
      anon_sym_xml,
  [1722] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(329), 1,
      sym__dec_num,
  [1729] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(331), 1,
      sym_name,
  [1736] = 1,
    ACTIONS(333), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1741] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(335), 1,
      sym_name,
  [1748] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(337), 1,
      sym_eq,
  [1755] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(339), 1,
      sym_name,
  [1762] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(341), 1,
      sym_name,
  [1769] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(343), 1,
      anon_sym_QMARK_GT,
  [1776] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(345), 1,
      anon_sym_LT,
  [1783] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(347), 1,
      anon_sym_GT,
  [1790] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(349), 1,
      anon_sym_COLON,
  [1797] = 2,
    ACTIONS(305), 1,
      anon_sym_QMARK_GT,
    ACTIONS(351), 1,
      sym__ws,
  [1804] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(353), 1,
      sym_eq,
  [1811] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(355), 1,
      ts_builtin_sym_end,
  [1818] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(357), 1,
      anon_sym_SEMI,
  [1825] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(359), 1,
      sym_cdata_end,
  [1832] = 2,
    ACTIONS(361), 1,
      anon_sym_QMARK_GT,
    ACTIONS(363), 1,
      sym__ws,
  [1839] = 2,
    ACTIONS(365), 1,
      anon_sym_GT,
    ACTIONS(367), 1,
      sym__ws,
  [1846] = 2,
    ACTIONS(369), 1,
      anon_sym_GT,
    ACTIONS(371), 1,
      sym__ws,
  [1853] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(373), 1,
      sym_name,
  [1860] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(375), 1,
      anon_sym_SEMI,
  [1867] = 2,
    ACTIONS(377), 1,
      anon_sym_QMARK_GT,
    ACTIONS(379), 1,
      sym__ws,
  [1874] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(381), 1,
      anon_sym_version,
  [1881] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(383), 1,
      anon_sym_GT,
  [1888] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(385), 1,
      sym_name,
  [1895] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(387), 1,
      sym_name,
  [1902] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(389), 1,
      sym_name,
  [1909] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(391), 1,
      sym_name,
  [1916] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(393), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 190,
  [SMALL_STATE(7)] = 236,
  [SMALL_STATE(8)] = 282,
  [SMALL_STATE(9)] = 328,
  [SMALL_STATE(10)] = 374,
  [SMALL_STATE(11)] = 417,
  [SMALL_STATE(12)] = 442,
  [SMALL_STATE(13)] = 467,
  [SMALL_STATE(14)] = 483,
  [SMALL_STATE(15)] = 499,
  [SMALL_STATE(16)] = 515,
  [SMALL_STATE(17)] = 531,
  [SMALL_STATE(18)] = 553,
  [SMALL_STATE(19)] = 569,
  [SMALL_STATE(20)] = 585,
  [SMALL_STATE(21)] = 601,
  [SMALL_STATE(22)] = 619,
  [SMALL_STATE(23)] = 635,
  [SMALL_STATE(24)] = 657,
  [SMALL_STATE(25)] = 673,
  [SMALL_STATE(26)] = 689,
  [SMALL_STATE(27)] = 705,
  [SMALL_STATE(28)] = 721,
  [SMALL_STATE(29)] = 737,
  [SMALL_STATE(30)] = 753,
  [SMALL_STATE(31)] = 775,
  [SMALL_STATE(32)] = 791,
  [SMALL_STATE(33)] = 807,
  [SMALL_STATE(34)] = 829,
  [SMALL_STATE(35)] = 845,
  [SMALL_STATE(36)] = 861,
  [SMALL_STATE(37)] = 877,
  [SMALL_STATE(38)] = 893,
  [SMALL_STATE(39)] = 915,
  [SMALL_STATE(40)] = 937,
  [SMALL_STATE(41)] = 952,
  [SMALL_STATE(42)] = 975,
  [SMALL_STATE(43)] = 998,
  [SMALL_STATE(44)] = 1021,
  [SMALL_STATE(45)] = 1044,
  [SMALL_STATE(46)] = 1061,
  [SMALL_STATE(47)] = 1074,
  [SMALL_STATE(48)] = 1091,
  [SMALL_STATE(49)] = 1103,
  [SMALL_STATE(50)] = 1115,
  [SMALL_STATE(51)] = 1131,
  [SMALL_STATE(52)] = 1143,
  [SMALL_STATE(53)] = 1155,
  [SMALL_STATE(54)] = 1169,
  [SMALL_STATE(55)] = 1181,
  [SMALL_STATE(56)] = 1195,
  [SMALL_STATE(57)] = 1207,
  [SMALL_STATE(58)] = 1219,
  [SMALL_STATE(59)] = 1231,
  [SMALL_STATE(60)] = 1245,
  [SMALL_STATE(61)] = 1257,
  [SMALL_STATE(62)] = 1269,
  [SMALL_STATE(63)] = 1281,
  [SMALL_STATE(64)] = 1295,
  [SMALL_STATE(65)] = 1307,
  [SMALL_STATE(66)] = 1319,
  [SMALL_STATE(67)] = 1331,
  [SMALL_STATE(68)] = 1345,
  [SMALL_STATE(69)] = 1358,
  [SMALL_STATE(70)] = 1371,
  [SMALL_STATE(71)] = 1384,
  [SMALL_STATE(72)] = 1397,
  [SMALL_STATE(73)] = 1410,
  [SMALL_STATE(74)] = 1423,
  [SMALL_STATE(75)] = 1436,
  [SMALL_STATE(76)] = 1449,
  [SMALL_STATE(77)] = 1462,
  [SMALL_STATE(78)] = 1475,
  [SMALL_STATE(79)] = 1486,
  [SMALL_STATE(80)] = 1499,
  [SMALL_STATE(81)] = 1512,
  [SMALL_STATE(82)] = 1525,
  [SMALL_STATE(83)] = 1536,
  [SMALL_STATE(84)] = 1549,
  [SMALL_STATE(85)] = 1560,
  [SMALL_STATE(86)] = 1573,
  [SMALL_STATE(87)] = 1586,
  [SMALL_STATE(88)] = 1592,
  [SMALL_STATE(89)] = 1598,
  [SMALL_STATE(90)] = 1608,
  [SMALL_STATE(91)] = 1618,
  [SMALL_STATE(92)] = 1624,
  [SMALL_STATE(93)] = 1630,
  [SMALL_STATE(94)] = 1636,
  [SMALL_STATE(95)] = 1642,
  [SMALL_STATE(96)] = 1648,
  [SMALL_STATE(97)] = 1658,
  [SMALL_STATE(98)] = 1665,
  [SMALL_STATE(99)] = 1670,
  [SMALL_STATE(100)] = 1677,
  [SMALL_STATE(101)] = 1684,
  [SMALL_STATE(102)] = 1691,
  [SMALL_STATE(103)] = 1698,
  [SMALL_STATE(104)] = 1705,
  [SMALL_STATE(105)] = 1710,
  [SMALL_STATE(106)] = 1715,
  [SMALL_STATE(107)] = 1722,
  [SMALL_STATE(108)] = 1729,
  [SMALL_STATE(109)] = 1736,
  [SMALL_STATE(110)] = 1741,
  [SMALL_STATE(111)] = 1748,
  [SMALL_STATE(112)] = 1755,
  [SMALL_STATE(113)] = 1762,
  [SMALL_STATE(114)] = 1769,
  [SMALL_STATE(115)] = 1776,
  [SMALL_STATE(116)] = 1783,
  [SMALL_STATE(117)] = 1790,
  [SMALL_STATE(118)] = 1797,
  [SMALL_STATE(119)] = 1804,
  [SMALL_STATE(120)] = 1811,
  [SMALL_STATE(121)] = 1818,
  [SMALL_STATE(122)] = 1825,
  [SMALL_STATE(123)] = 1832,
  [SMALL_STATE(124)] = 1839,
  [SMALL_STATE(125)] = 1846,
  [SMALL_STATE(126)] = 1853,
  [SMALL_STATE(127)] = 1860,
  [SMALL_STATE(128)] = 1867,
  [SMALL_STATE(129)] = 1874,
  [SMALL_STATE(130)] = 1881,
  [SMALL_STATE(131)] = 1888,
  [SMALL_STATE(132)] = 1895,
  [SMALL_STATE(133)] = 1902,
  [SMALL_STATE(134)] = 1909,
  [SMALL_STATE(135)] = 1916,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(133),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(108),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(70),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(21),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(50),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(131),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 5, .production_id = 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 5, .production_id = 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 3, .production_id = 1),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 3, .production_id = 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 4, .production_id = 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 4, .production_id = 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag_element, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag_element, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__content, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 4, .production_id = 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 4, .production_id = 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata_sect, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cdata_sect, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 3, .production_id = 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 3, .production_id = 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag_element, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag_element, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 3, .production_id = 1),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 3, .production_id = 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_ref, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_ref, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(30),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(30),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(135),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attr_value_repeat1, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 5),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 5),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 4, .production_id = 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 4, .production_id = 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(110),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(73),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(33),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 5, .production_id = 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 5, .production_id = 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag_element, 4),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag_element, 4),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata_sect, 2),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cdata_sect, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 4),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 1),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__content, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata, 1),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pi_repeat1, 2),
  [241] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(74),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [252] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(77),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [259] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(79),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_empty_element_repeat1, 2),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_empty_element_repeat1, 2), SHIFT_REPEAT(45),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ns_decl, 5, .production_id = 6),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_value, 3),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_attr, 5, .production_id = 7),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_value, 2),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_attr, 3, .production_id = 4),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 4, .production_id = 2),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_encoding_value, 3),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 6, .production_id = 2),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_version_value, 3),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_version, 4, .production_id = 3),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_encoding, 4, .production_id = 5),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 5, .production_id = 2),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [355] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_xml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
