#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 4

enum {
  anon_sym_LT_QMARK = 1,
  anon_sym_QMARK_GT = 2,
  anon_sym_LT = 3,
  anon_sym_SLASH_GT = 4,
  anon_sym_GT = 5,
  anon_sym_LT_SLASH = 6,
  anon_sym_xmlns = 7,
  anon_sym_COLON = 8,
  aux_sym_attr_value_token1 = 9,
  anon_sym_LT_QMARKxml = 10,
  anon_sym_version = 11,
  anon_sym_encoding = 12,
  sym_name = 13,
  anon_sym_LT_BANG_DASH_DASH = 14,
  anon_sym_DASH_DASH_GT = 15,
  sym_char_data = 16,
  sym_char_ref = 17,
  sym_cdata_start = 18,
  sym_cdata_end = 19,
  anon_sym_AMP = 20,
  sym__char = 21,
  sym__ws = 22,
  sym__eq = 23,
  anon_sym_DQUOTE = 24,
  anon_sym_SQUOTE = 25,
  sym__dec_num = 26,
  sym__encoding = 27,
  sym_xml_file = 28,
  sym_pi = 29,
  sym_element = 30,
  sym_empty_element = 31,
  sym_tag_start = 32,
  sym_tag_end = 33,
  aux_sym__content = 34,
  sym_attribute = 35,
  sym_ns_decl = 36,
  sym_xml_attr = 37,
  sym_attr_value = 38,
  sym_xml_decl = 39,
  sym_xml_version = 40,
  sym_xml_encoding = 41,
  sym_comment = 42,
  sym__cdata_sect = 43,
  sym_cdata = 44,
  sym__ref = 45,
  sym_entity_ref = 46,
  sym__misc = 47,
  sym__quote = 48,
  aux_sym_xml_file_repeat1 = 49,
  aux_sym_pi_repeat1 = 50,
  aux_sym_empty_element_repeat1 = 51,
  aux_sym_attr_value_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_xmlns] = "xmlns",
  [anon_sym_COLON] = ":",
  [aux_sym_attr_value_token1] = "attr_value_token1",
  [anon_sym_LT_QMARKxml] = "<\?xml",
  [anon_sym_version] = "version",
  [anon_sym_encoding] = "encoding",
  [sym_name] = "name",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_char_data] = "char_data",
  [sym_char_ref] = "char_ref",
  [sym_cdata_start] = "cdata_start",
  [sym_cdata_end] = "cdata_end",
  [anon_sym_AMP] = "&",
  [sym__char] = "_char",
  [sym__ws] = "_ws",
  [sym__eq] = "_eq",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym__dec_num] = "_dec_num",
  [sym__encoding] = "_encoding",
  [sym_xml_file] = "xml_file",
  [sym_pi] = "pi",
  [sym_element] = "element",
  [sym_empty_element] = "empty_element",
  [sym_tag_start] = "tag_start",
  [sym_tag_end] = "tag_end",
  [aux_sym__content] = "_content",
  [sym_attribute] = "attribute",
  [sym_ns_decl] = "ns_decl",
  [sym_xml_attr] = "xml_attr",
  [sym_attr_value] = "attr_value",
  [sym_xml_decl] = "xml_decl",
  [sym_xml_version] = "xml_version",
  [sym_xml_encoding] = "xml_encoding",
  [sym_comment] = "comment",
  [sym__cdata_sect] = "_cdata_sect",
  [sym_cdata] = "cdata",
  [sym__ref] = "_ref",
  [sym_entity_ref] = "entity_ref",
  [sym__misc] = "_misc",
  [sym__quote] = "_quote",
  [aux_sym_xml_file_repeat1] = "xml_file_repeat1",
  [aux_sym_pi_repeat1] = "pi_repeat1",
  [aux_sym_empty_element_repeat1] = "empty_element_repeat1",
  [aux_sym_attr_value_repeat1] = "attr_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_xmlns] = anon_sym_xmlns,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_attr_value_token1] = aux_sym_attr_value_token1,
  [anon_sym_LT_QMARKxml] = anon_sym_LT_QMARKxml,
  [anon_sym_version] = anon_sym_version,
  [anon_sym_encoding] = anon_sym_encoding,
  [sym_name] = sym_name,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_char_data] = sym_char_data,
  [sym_char_ref] = sym_char_ref,
  [sym_cdata_start] = sym_cdata_start,
  [sym_cdata_end] = sym_cdata_end,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym__char] = sym__char,
  [sym__ws] = sym__ws,
  [sym__eq] = sym__eq,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym__dec_num] = sym__dec_num,
  [sym__encoding] = sym__encoding,
  [sym_xml_file] = sym_xml_file,
  [sym_pi] = sym_pi,
  [sym_element] = sym_element,
  [sym_empty_element] = sym_empty_element,
  [sym_tag_start] = sym_tag_start,
  [sym_tag_end] = sym_tag_end,
  [aux_sym__content] = aux_sym__content,
  [sym_attribute] = sym_attribute,
  [sym_ns_decl] = sym_ns_decl,
  [sym_xml_attr] = sym_xml_attr,
  [sym_attr_value] = sym_attr_value,
  [sym_xml_decl] = sym_xml_decl,
  [sym_xml_version] = sym_xml_version,
  [sym_xml_encoding] = sym_xml_encoding,
  [sym_comment] = sym_comment,
  [sym__cdata_sect] = sym__cdata_sect,
  [sym_cdata] = sym_cdata,
  [sym__ref] = sym__ref,
  [sym_entity_ref] = sym_entity_ref,
  [sym__misc] = sym__misc,
  [sym__quote] = sym__quote,
  [aux_sym_xml_file_repeat1] = aux_sym_xml_file_repeat1,
  [aux_sym_pi_repeat1] = aux_sym_pi_repeat1,
  [aux_sym_empty_element_repeat1] = aux_sym_empty_element_repeat1,
  [aux_sym_attr_value_repeat1] = aux_sym_attr_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_xmlns] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attr_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_QMARKxml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_version] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_encoding] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_char_data] = {
    .visible = true,
    .named = true,
  },
  [sym_char_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata_start] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym__eq] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__dec_num] = {
    .visible = false,
    .named = true,
  },
  [sym__encoding] = {
    .visible = false,
    .named = true,
  },
  [sym_xml_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pi] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_element] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__content] = {
    .visible = false,
    .named = false,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_ns_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_attr] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_value] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_version] = {
    .visible = true,
    .named = true,
  },
  [sym_xml_encoding] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__cdata_sect] = {
    .visible = false,
    .named = true,
  },
  [sym_cdata] = {
    .visible = true,
    .named = true,
  },
  [sym__ref] = {
    .visible = false,
    .named = true,
  },
  [sym_entity_ref] = {
    .visible = true,
    .named = true,
  },
  [sym__misc] = {
    .visible = false,
    .named = true,
  },
  [sym__quote] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_xml_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pi_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_empty_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attr_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_attr_name = 1,
  field_ns_prefix = 2,
  field_prefix = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attr_name] = "attr_name",
  [field_ns_prefix] = "ns_prefix",
  [field_prefix] = "prefix",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_attr_name, 0},
  [1] =
    {field_prefix, 2},
  [2] =
    {field_attr_name, 2},
    {field_ns_prefix, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 4,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 40,
  [43] = 43,
  [44] = 43,
  [45] = 45,
  [46] = 35,
  [47] = 17,
  [48] = 15,
  [49] = 28,
  [50] = 14,
  [51] = 51,
  [52] = 52,
  [53] = 37,
  [54] = 54,
  [55] = 27,
  [56] = 13,
  [57] = 21,
  [58] = 30,
  [59] = 19,
  [60] = 29,
  [61] = 18,
  [62] = 62,
  [63] = 31,
  [64] = 23,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 68,
  [72] = 72,
  [73] = 66,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 74,
  [78] = 70,
  [79] = 79,
  [80] = 79,
  [81] = 81,
  [82] = 76,
  [83] = 75,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 105,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 101,
  [121] = 121,
  [122] = 97,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 121,
  [127] = 127,
  [128] = 119,
  [129] = 109,
  [130] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '=') ADVANCE(78);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == '-') ADVANCE(74);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == '?') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == ']') ADVANCE(76);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(55);
      END_STATE();
    case 5:
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '?') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(30);
      if (lookahead == 'v') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '[') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(64);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == ';') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == ';') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(50);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(70);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(65);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(69);
      END_STATE();
    case 18:
      if (lookahead == 'C') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 'D') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == ']') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'g') ADVANCE(58);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 37:
      if (lookahead == 'x') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 38:
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 39:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 40:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 43:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == '<') ADVANCE(73);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      if (lookahead == '"') ADVANCE(79);
      if (lookahead == '\'') ADVANCE(80);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '=') ADVANCE(78);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead == '?') ADVANCE(13);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead == '?') ADVANCE(46);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '?') ADVANCE(38);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_xmlns);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_attr_value_token1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LT_QMARKxml);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_version);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_encoding);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'l') ADVANCE(61);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'm') ADVANCE(59);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(62);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(53);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_char_data);
      if (lookahead == '&') ADVANCE(71);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_char_data);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_char_ref);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_cdata_start);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_cdata_end);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '#') ADVANCE(37);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__char);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '?') ADVANCE(46);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '-') ADVANCE(15);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == '>') ADVANCE(47);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__char);
      if (lookahead == ']') ADVANCE(14);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__ws);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__eq);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__dec_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__encoding);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 44},
  [2] = {.lex_state = 66},
  [3] = {.lex_state = 66},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 66},
  [14] = {.lex_state = 66},
  [15] = {.lex_state = 66},
  [16] = {.lex_state = 43},
  [17] = {.lex_state = 66},
  [18] = {.lex_state = 66},
  [19] = {.lex_state = 66},
  [20] = {.lex_state = 66},
  [21] = {.lex_state = 66},
  [22] = {.lex_state = 43},
  [23] = {.lex_state = 66},
  [24] = {.lex_state = 66},
  [25] = {.lex_state = 66},
  [26] = {.lex_state = 43},
  [27] = {.lex_state = 66},
  [28] = {.lex_state = 66},
  [29] = {.lex_state = 66},
  [30] = {.lex_state = 66},
  [31] = {.lex_state = 66},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 43},
  [35] = {.lex_state = 66},
  [36] = {.lex_state = 66},
  [37] = {.lex_state = 66},
  [38] = {.lex_state = 66},
  [39] = {.lex_state = 66},
  [40] = {.lex_state = 44},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 44},
  [43] = {.lex_state = 44},
  [44] = {.lex_state = 44},
  [45] = {.lex_state = 44},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 43},
  [48] = {.lex_state = 43},
  [49] = {.lex_state = 43},
  [50] = {.lex_state = 43},
  [51] = {.lex_state = 44},
  [52] = {.lex_state = 44},
  [53] = {.lex_state = 43},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 43},
  [56] = {.lex_state = 43},
  [57] = {.lex_state = 43},
  [58] = {.lex_state = 43},
  [59] = {.lex_state = 43},
  [60] = {.lex_state = 43},
  [61] = {.lex_state = 43},
  [62] = {.lex_state = 44},
  [63] = {.lex_state = 43},
  [64] = {.lex_state = 43},
  [65] = {.lex_state = 44},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 44},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 44},
  [72] = {.lex_state = 44},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 44},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 44},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 44},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 44},
  [85] = {.lex_state = 44},
  [86] = {.lex_state = 44},
  [87] = {.lex_state = 44},
  [88] = {.lex_state = 44},
  [89] = {.lex_state = 44},
  [90] = {.lex_state = 44},
  [91] = {.lex_state = 44},
  [92] = {.lex_state = 44},
  [93] = {.lex_state = 44},
  [94] = {.lex_state = 44},
  [95] = {.lex_state = 5},
  [96] = {.lex_state = 44},
  [97] = {.lex_state = 44},
  [98] = {.lex_state = 44},
  [99] = {.lex_state = 44},
  [100] = {.lex_state = 44},
  [101] = {.lex_state = 44},
  [102] = {.lex_state = 44},
  [103] = {.lex_state = 44},
  [104] = {.lex_state = 44},
  [105] = {.lex_state = 40},
  [106] = {.lex_state = 44},
  [107] = {.lex_state = 40},
  [108] = {.lex_state = 39},
  [109] = {.lex_state = 40},
  [110] = {.lex_state = 44},
  [111] = {.lex_state = 44},
  [112] = {.lex_state = 5},
  [113] = {.lex_state = 44},
  [114] = {.lex_state = 44},
  [115] = {.lex_state = 44},
  [116] = {.lex_state = 40},
  [117] = {.lex_state = 40},
  [118] = {.lex_state = 40},
  [119] = {.lex_state = 40},
  [120] = {.lex_state = 44},
  [121] = {.lex_state = 44},
  [122] = {.lex_state = 44},
  [123] = {.lex_state = 44},
  [124] = {.lex_state = 44},
  [125] = {.lex_state = 44},
  [126] = {.lex_state = 44},
  [127] = {.lex_state = 44},
  [128] = {.lex_state = 40},
  [129] = {.lex_state = 40},
  [130] = {.lex_state = 40},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_attr_value_token1] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [sym_char_ref] = ACTIONS(1),
    [sym_cdata_start] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym__char] = ACTIONS(1),
    [sym__ws] = ACTIONS(3),
    [sym__eq] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_xml_file] = STATE(123),
    [sym_element] = STATE(33),
    [sym_empty_element] = STATE(63),
    [sym_tag_start] = STATE(2),
    [sym_xml_decl] = STATE(65),
    [anon_sym_LT] = ACTIONS(5),
    [anon_sym_LT_QMARKxml] = ACTIONS(7),
    [sym__ws] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(19), 1,
      sym_char_data,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(4), 1,
      aux_sym__content,
    STATE(31), 1,
      sym_empty_element,
    STATE(50), 1,
      sym_tag_end,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [48] = 14,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_char_data,
    STATE(3), 1,
      sym_tag_start,
    STATE(7), 1,
      aux_sym__content,
    STATE(14), 1,
      sym_tag_end,
    STATE(31), 1,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [96] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(31), 1,
      sym_empty_element,
    STATE(55), 1,
      sym_tag_end,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [141] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(17), 1,
      sym_tag_end,
    STATE(31), 1,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [186] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(31), 1,
      sym_empty_element,
    STATE(47), 1,
      sym_tag_end,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [231] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(27), 1,
      sym_tag_end,
    STATE(31), 1,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [276] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(3), 1,
      sym_tag_start,
    STATE(5), 1,
      aux_sym__content,
    STATE(27), 1,
      sym_tag_end,
    STATE(31), 1,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [321] = 13,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LT_QMARK,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(21), 1,
      sym_char_ref,
    ACTIONS(23), 1,
      sym_cdata_start,
    ACTIONS(25), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(6), 1,
      aux_sym__content,
    STATE(31), 1,
      sym_empty_element,
    STATE(55), 1,
      sym_tag_end,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [366] = 12,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(31), 1,
      anon_sym_LT_QMARK,
    ACTIONS(34), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(42), 1,
      sym_char_ref,
    ACTIONS(45), 1,
      sym_cdata_start,
    ACTIONS(48), 1,
      anon_sym_AMP,
    STATE(3), 1,
      sym_tag_start,
    STATE(10), 1,
      aux_sym__content,
    STATE(31), 1,
      sym_empty_element,
    STATE(20), 6,
      sym_pi,
      sym_element,
      sym_comment,
      sym__cdata_sect,
      sym__ref,
      sym_entity_ref,
  [408] = 7,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(51), 1,
      aux_sym_attr_value_token1,
    ACTIONS(53), 1,
      sym_char_ref,
    ACTIONS(55), 1,
      anon_sym_AMP,
    STATE(93), 1,
      sym__quote,
    ACTIONS(57), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(12), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [433] = 7,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(55), 1,
      anon_sym_AMP,
    ACTIONS(59), 1,
      aux_sym_attr_value_token1,
    ACTIONS(61), 1,
      sym_char_ref,
    STATE(92), 1,
      sym__quote,
    ACTIONS(63), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(32), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [458] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(67), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(65), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [474] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(71), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(69), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [490] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(75), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(73), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [506] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(83), 1,
      sym__char,
    STATE(34), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [528] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(87), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(85), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [544] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(91), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(89), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [560] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(95), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(93), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [576] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(101), 1,
      sym_char_data,
    ACTIONS(99), 2,
      anon_sym_LT,
      anon_sym_AMP,
    ACTIONS(97), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [594] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(105), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(103), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [610] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(107), 1,
      sym__char,
    STATE(26), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [632] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(111), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(109), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [648] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(115), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(113), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [664] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(119), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(117), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [680] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(83), 1,
      sym__char,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(34), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [702] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(125), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(123), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [718] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(129), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(127), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [734] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(133), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(131), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [750] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(137), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(135), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [766] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(141), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(139), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [782] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(143), 1,
      aux_sym_attr_value_token1,
    ACTIONS(146), 1,
      sym_char_ref,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(152), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(32), 3,
      sym__ref,
      sym_entity_ref,
      aux_sym_attr_value_repeat1,
  [804] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(79), 1,
      anon_sym_LT_QMARK,
    ACTIONS(81), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      sym__char,
    STATE(16), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [826] = 6,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 1,
      anon_sym_LT_QMARK,
    ACTIONS(163), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(166), 1,
      sym__char,
    STATE(34), 4,
      sym_pi,
      sym_comment,
      sym__misc,
      aux_sym_xml_file_repeat1,
  [848] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(171), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(169), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [864] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(175), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(173), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [880] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(179), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(177), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [896] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(183), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(181), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [912] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(187), 3,
      anon_sym_LT,
      sym_char_data,
      anon_sym_AMP,
    ACTIONS(185), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [928] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(189), 1,
      anon_sym_SLASH_GT,
    ACTIONS(191), 1,
      anon_sym_GT,
    ACTIONS(193), 1,
      anon_sym_xmlns,
    ACTIONS(195), 1,
      sym_name,
    STATE(94), 1,
      sym_attribute,
    STATE(88), 2,
      sym_ns_decl,
      sym_xml_attr,
  [951] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(197), 2,
      anon_sym_LT,
      anon_sym_AMP,
    ACTIONS(37), 5,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
      anon_sym_LT_BANG_DASH_DASH,
      sym_char_ref,
      sym_cdata_start,
  [966] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(191), 1,
      anon_sym_GT,
    ACTIONS(193), 1,
      anon_sym_xmlns,
    ACTIONS(195), 1,
      sym_name,
    ACTIONS(199), 1,
      anon_sym_SLASH_GT,
    STATE(94), 1,
      sym_attribute,
    STATE(88), 2,
      sym_ns_decl,
      sym_xml_attr,
  [989] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(193), 1,
      anon_sym_xmlns,
    ACTIONS(195), 1,
      sym_name,
    ACTIONS(201), 1,
      anon_sym_SLASH_GT,
    ACTIONS(203), 1,
      anon_sym_GT,
    STATE(94), 1,
      sym_attribute,
    STATE(88), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1012] = 7,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(193), 1,
      anon_sym_xmlns,
    ACTIONS(195), 1,
      sym_name,
    ACTIONS(203), 1,
      anon_sym_GT,
    ACTIONS(205), 1,
      anon_sym_SLASH_GT,
    STATE(94), 1,
      sym_attribute,
    STATE(88), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1035] = 5,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(193), 1,
      anon_sym_xmlns,
    ACTIONS(195), 1,
      sym_name,
    STATE(94), 1,
      sym_attribute,
    STATE(88), 2,
      sym_ns_decl,
      sym_xml_attr,
  [1052] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(171), 2,
      aux_sym_attr_value_token1,
      anon_sym_AMP,
    ACTIONS(169), 3,
      sym_char_ref,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1065] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(87), 1,
      sym__char,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1077] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(75), 1,
      sym__char,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1089] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(129), 1,
      sym__char,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1101] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(71), 1,
      sym__char,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1113] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(11), 1,
      sym__quote,
    STATE(91), 1,
      sym_attr_value,
    ACTIONS(207), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1127] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(11), 1,
      sym__quote,
    STATE(90), 1,
      sym_attr_value,
    ACTIONS(207), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1141] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(179), 1,
      sym__char,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1153] = 5,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(209), 1,
      sym_cdata_end,
    ACTIONS(211), 1,
      sym__char,
    STATE(69), 1,
      aux_sym_pi_repeat1,
    STATE(115), 1,
      sym_cdata,
  [1169] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(125), 1,
      sym__char,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1181] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(67), 1,
      sym__char,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1193] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(105), 1,
      sym__char,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1205] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(137), 1,
      sym__char,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1217] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(95), 1,
      sym__char,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1229] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(133), 1,
      sym__char,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1241] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(91), 1,
      sym__char,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1253] = 4,
    ACTIONS(9), 1,
      sym__ws,
    STATE(11), 1,
      sym__quote,
    STATE(96), 1,
      sym_attr_value,
    ACTIONS(207), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1267] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(141), 1,
      sym__char,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1279] = 3,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(111), 1,
      sym__char,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_LT_QMARK,
      anon_sym_LT_BANG_DASH_DASH,
  [1291] = 5,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(213), 1,
      anon_sym_LT,
    STATE(2), 1,
      sym_tag_start,
    STATE(22), 1,
      sym_element,
    STATE(63), 1,
      sym_empty_element,
  [1307] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(215), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(217), 1,
      sym__char,
    STATE(66), 1,
      aux_sym_pi_repeat1,
  [1320] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(215), 1,
      sym_cdata_end,
    ACTIONS(220), 1,
      sym__char,
    STATE(67), 1,
      aux_sym_pi_repeat1,
  [1333] = 4,
    ACTIONS(223), 1,
      anon_sym_SLASH_GT,
    ACTIONS(225), 1,
      anon_sym_GT,
    ACTIONS(227), 1,
      sym__ws,
    STATE(77), 1,
      aux_sym_empty_element_repeat1,
  [1346] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(229), 1,
      sym_cdata_end,
    ACTIONS(231), 1,
      sym__char,
    STATE(67), 1,
      aux_sym_pi_repeat1,
  [1359] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(233), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(235), 1,
      sym__char,
    STATE(80), 1,
      aux_sym_pi_repeat1,
  [1372] = 4,
    ACTIONS(225), 1,
      anon_sym_GT,
    ACTIONS(237), 1,
      anon_sym_SLASH_GT,
    ACTIONS(239), 1,
      sym__ws,
    STATE(74), 1,
      aux_sym_empty_element_repeat1,
  [1385] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(108), 1,
      sym__quote,
    ACTIONS(241), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1396] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(215), 1,
      anon_sym_QMARK_GT,
    ACTIONS(243), 1,
      sym__char,
    STATE(73), 1,
      aux_sym_pi_repeat1,
  [1409] = 4,
    ACTIONS(201), 1,
      anon_sym_SLASH_GT,
    ACTIONS(203), 1,
      anon_sym_GT,
    ACTIONS(246), 1,
      sym__ws,
    STATE(85), 1,
      aux_sym_empty_element_repeat1,
  [1422] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(248), 1,
      anon_sym_QMARK_GT,
    ACTIONS(250), 1,
      sym__char,
    STATE(73), 1,
      aux_sym_pi_repeat1,
  [1435] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(252), 1,
      anon_sym_QMARK_GT,
    ACTIONS(254), 1,
      sym__char,
    STATE(75), 1,
      aux_sym_pi_repeat1,
  [1448] = 4,
    ACTIONS(203), 1,
      anon_sym_GT,
    ACTIONS(205), 1,
      anon_sym_SLASH_GT,
    ACTIONS(256), 1,
      sym__ws,
    STATE(85), 1,
      aux_sym_empty_element_repeat1,
  [1461] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(258), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(260), 1,
      sym__char,
    STATE(79), 1,
      aux_sym_pi_repeat1,
  [1474] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(262), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(264), 1,
      sym__char,
    STATE(66), 1,
      aux_sym_pi_repeat1,
  [1487] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(264), 1,
      sym__char,
    ACTIONS(266), 1,
      anon_sym_DASH_DASH_GT,
    STATE(66), 1,
      aux_sym_pi_repeat1,
  [1500] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(104), 1,
      sym__quote,
    ACTIONS(268), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1511] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(270), 1,
      anon_sym_QMARK_GT,
    ACTIONS(272), 1,
      sym__char,
    STATE(83), 1,
      aux_sym_pi_repeat1,
  [1524] = 4,
    ACTIONS(3), 1,
      sym__ws,
    ACTIONS(250), 1,
      sym__char,
    ACTIONS(274), 1,
      anon_sym_QMARK_GT,
    STATE(73), 1,
      aux_sym_pi_repeat1,
  [1537] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(114), 1,
      sym__quote,
    ACTIONS(276), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1548] = 3,
    ACTIONS(280), 1,
      sym__ws,
    STATE(85), 1,
      aux_sym_empty_element_repeat1,
    ACTIONS(278), 2,
      anon_sym_SLASH_GT,
      anon_sym_GT,
  [1559] = 3,
    ACTIONS(9), 1,
      sym__ws,
    STATE(98), 1,
      sym__quote,
    ACTIONS(283), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1570] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(285), 1,
      anon_sym_COLON,
    ACTIONS(287), 1,
      sym__eq,
  [1580] = 1,
    ACTIONS(289), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1586] = 3,
    ACTIONS(291), 1,
      anon_sym_QMARK_GT,
    ACTIONS(293), 1,
      sym__ws,
    STATE(102), 1,
      sym_xml_encoding,
  [1596] = 1,
    ACTIONS(295), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1602] = 1,
    ACTIONS(297), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1608] = 1,
    ACTIONS(299), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1614] = 1,
    ACTIONS(301), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1620] = 1,
    ACTIONS(278), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1626] = 3,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(303), 1,
      anon_sym_QMARK_GT,
    ACTIONS(305), 1,
      anon_sym_encoding,
  [1636] = 1,
    ACTIONS(307), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym__ws,
  [1642] = 2,
    ACTIONS(309), 1,
      anon_sym_GT,
    ACTIONS(311), 1,
      sym__ws,
  [1649] = 1,
    ACTIONS(313), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1654] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(315), 1,
      anon_sym_LT,
  [1661] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(317), 1,
      sym__eq,
  [1668] = 2,
    ACTIONS(319), 1,
      anon_sym_QMARK_GT,
    ACTIONS(321), 1,
      sym__ws,
  [1675] = 2,
    ACTIONS(303), 1,
      anon_sym_QMARK_GT,
    ACTIONS(323), 1,
      sym__ws,
  [1682] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(325), 1,
      anon_sym_LT,
  [1689] = 1,
    ACTIONS(327), 2,
      anon_sym_QMARK_GT,
      sym__ws,
  [1694] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(329), 1,
      sym_name,
  [1701] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(331), 1,
      anon_sym_COLON,
  [1708] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(333), 1,
      sym_name,
  [1715] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(335), 1,
      sym__encoding,
  [1722] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(337), 1,
      sym_name,
  [1729] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(339), 1,
      sym__eq,
  [1736] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(341), 1,
      sym__eq,
  [1743] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(343), 1,
      anon_sym_version,
  [1750] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(345), 1,
      anon_sym_LT,
  [1757] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(347), 1,
      sym__dec_num,
  [1764] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(349), 1,
      sym_cdata_end,
  [1771] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(351), 1,
      sym_name,
  [1778] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(353), 1,
      sym_name,
  [1785] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(355), 1,
      sym_name,
  [1792] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(357), 1,
      sym_name,
  [1799] = 2,
    ACTIONS(359), 1,
      anon_sym_QMARK_GT,
    ACTIONS(361), 1,
      sym__ws,
  [1806] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(363), 1,
      anon_sym_GT,
  [1813] = 2,
    ACTIONS(365), 1,
      anon_sym_GT,
    ACTIONS(367), 1,
      sym__ws,
  [1820] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(369), 1,
      ts_builtin_sym_end,
  [1827] = 2,
    ACTIONS(371), 1,
      sym__ws,
    STATE(89), 1,
      sym_xml_version,
  [1834] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(373), 1,
      anon_sym_QMARK_GT,
  [1841] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(375), 1,
      anon_sym_GT,
  [1848] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(377), 1,
      sym__eq,
  [1855] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(379), 1,
      sym_name,
  [1862] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(381), 1,
      sym_name,
  [1869] = 2,
    ACTIONS(9), 1,
      sym__ws,
    ACTIONS(383), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 186,
  [SMALL_STATE(7)] = 231,
  [SMALL_STATE(8)] = 276,
  [SMALL_STATE(9)] = 321,
  [SMALL_STATE(10)] = 366,
  [SMALL_STATE(11)] = 408,
  [SMALL_STATE(12)] = 433,
  [SMALL_STATE(13)] = 458,
  [SMALL_STATE(14)] = 474,
  [SMALL_STATE(15)] = 490,
  [SMALL_STATE(16)] = 506,
  [SMALL_STATE(17)] = 528,
  [SMALL_STATE(18)] = 544,
  [SMALL_STATE(19)] = 560,
  [SMALL_STATE(20)] = 576,
  [SMALL_STATE(21)] = 594,
  [SMALL_STATE(22)] = 610,
  [SMALL_STATE(23)] = 632,
  [SMALL_STATE(24)] = 648,
  [SMALL_STATE(25)] = 664,
  [SMALL_STATE(26)] = 680,
  [SMALL_STATE(27)] = 702,
  [SMALL_STATE(28)] = 718,
  [SMALL_STATE(29)] = 734,
  [SMALL_STATE(30)] = 750,
  [SMALL_STATE(31)] = 766,
  [SMALL_STATE(32)] = 782,
  [SMALL_STATE(33)] = 804,
  [SMALL_STATE(34)] = 826,
  [SMALL_STATE(35)] = 848,
  [SMALL_STATE(36)] = 864,
  [SMALL_STATE(37)] = 880,
  [SMALL_STATE(38)] = 896,
  [SMALL_STATE(39)] = 912,
  [SMALL_STATE(40)] = 928,
  [SMALL_STATE(41)] = 951,
  [SMALL_STATE(42)] = 966,
  [SMALL_STATE(43)] = 989,
  [SMALL_STATE(44)] = 1012,
  [SMALL_STATE(45)] = 1035,
  [SMALL_STATE(46)] = 1052,
  [SMALL_STATE(47)] = 1065,
  [SMALL_STATE(48)] = 1077,
  [SMALL_STATE(49)] = 1089,
  [SMALL_STATE(50)] = 1101,
  [SMALL_STATE(51)] = 1113,
  [SMALL_STATE(52)] = 1127,
  [SMALL_STATE(53)] = 1141,
  [SMALL_STATE(54)] = 1153,
  [SMALL_STATE(55)] = 1169,
  [SMALL_STATE(56)] = 1181,
  [SMALL_STATE(57)] = 1193,
  [SMALL_STATE(58)] = 1205,
  [SMALL_STATE(59)] = 1217,
  [SMALL_STATE(60)] = 1229,
  [SMALL_STATE(61)] = 1241,
  [SMALL_STATE(62)] = 1253,
  [SMALL_STATE(63)] = 1267,
  [SMALL_STATE(64)] = 1279,
  [SMALL_STATE(65)] = 1291,
  [SMALL_STATE(66)] = 1307,
  [SMALL_STATE(67)] = 1320,
  [SMALL_STATE(68)] = 1333,
  [SMALL_STATE(69)] = 1346,
  [SMALL_STATE(70)] = 1359,
  [SMALL_STATE(71)] = 1372,
  [SMALL_STATE(72)] = 1385,
  [SMALL_STATE(73)] = 1396,
  [SMALL_STATE(74)] = 1409,
  [SMALL_STATE(75)] = 1422,
  [SMALL_STATE(76)] = 1435,
  [SMALL_STATE(77)] = 1448,
  [SMALL_STATE(78)] = 1461,
  [SMALL_STATE(79)] = 1474,
  [SMALL_STATE(80)] = 1487,
  [SMALL_STATE(81)] = 1500,
  [SMALL_STATE(82)] = 1511,
  [SMALL_STATE(83)] = 1524,
  [SMALL_STATE(84)] = 1537,
  [SMALL_STATE(85)] = 1548,
  [SMALL_STATE(86)] = 1559,
  [SMALL_STATE(87)] = 1570,
  [SMALL_STATE(88)] = 1580,
  [SMALL_STATE(89)] = 1586,
  [SMALL_STATE(90)] = 1596,
  [SMALL_STATE(91)] = 1602,
  [SMALL_STATE(92)] = 1608,
  [SMALL_STATE(93)] = 1614,
  [SMALL_STATE(94)] = 1620,
  [SMALL_STATE(95)] = 1626,
  [SMALL_STATE(96)] = 1636,
  [SMALL_STATE(97)] = 1642,
  [SMALL_STATE(98)] = 1649,
  [SMALL_STATE(99)] = 1654,
  [SMALL_STATE(100)] = 1661,
  [SMALL_STATE(101)] = 1668,
  [SMALL_STATE(102)] = 1675,
  [SMALL_STATE(103)] = 1682,
  [SMALL_STATE(104)] = 1689,
  [SMALL_STATE(105)] = 1694,
  [SMALL_STATE(106)] = 1701,
  [SMALL_STATE(107)] = 1708,
  [SMALL_STATE(108)] = 1715,
  [SMALL_STATE(109)] = 1722,
  [SMALL_STATE(110)] = 1729,
  [SMALL_STATE(111)] = 1736,
  [SMALL_STATE(112)] = 1743,
  [SMALL_STATE(113)] = 1750,
  [SMALL_STATE(114)] = 1757,
  [SMALL_STATE(115)] = 1764,
  [SMALL_STATE(116)] = 1771,
  [SMALL_STATE(117)] = 1778,
  [SMALL_STATE(118)] = 1785,
  [SMALL_STATE(119)] = 1792,
  [SMALL_STATE(120)] = 1799,
  [SMALL_STATE(121)] = 1806,
  [SMALL_STATE(122)] = 1813,
  [SMALL_STATE(123)] = 1820,
  [SMALL_STATE(124)] = 1827,
  [SMALL_STATE(125)] = 1834,
  [SMALL_STATE(126)] = 1841,
  [SMALL_STATE(127)] = 1848,
  [SMALL_STATE(128)] = 1855,
  [SMALL_STATE(129)] = 1862,
  [SMALL_STATE(130)] = 1869,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(129),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(128),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(70),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(20),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(54),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2), SHIFT_REPEAT(105),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 4),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 5),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 4),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 4),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_end, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_end, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__content, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 4),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 4),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_element, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_element, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 4),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 4),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(32),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(32),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_attr_value_repeat1, 2), SHIFT_REPEAT(116),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attr_value_repeat1, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_file, 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(109),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(78),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_xml_file_repeat1, 2), SHIFT_REPEAT(34),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_ref, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_ref, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cdata_sect, 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cdata_sect, 3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pi, 5),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pi, 5),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cdata_sect, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cdata_sect, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_start, 5),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_start, 5),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__content, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pi_repeat1, 2),
  [217] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(66),
  [220] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(67),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata, 1),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [243] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pi_repeat1, 2), SHIFT_REPEAT(73),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_empty_element_repeat1, 2),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_empty_element_repeat1, 2), SHIFT_REPEAT(45),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ns_decl, 5, .production_id = 2),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_attr, 5, .production_id = 3),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_value, 3),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_value, 2),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_attr, 3, .production_id = 1),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_encoding, 6),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 3),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 4),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_version, 6),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xml_decl, 5),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [369] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_xml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
